## TLC 2024 data collection

In [ ]:
import os, hashlib, requests
import pandas as pd
from tqdm import tqdm

# TLC Trip Data Downloader for 2024

BASE_URL = "https://d37ci6vzurychx.cloudfront.net/trip-data"
DEST_DIR = r"X:\data\raw\tlc\2024"
YEAR = "2024"

os.makedirs(DEST_DIR, exist_ok=True)

def sha256_checksum(file_path, chunk_size=8192):
    """Compute SHA256 checksum of a file."""
    sha = hashlib.sha256()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(chunk_size), b""):
            sha.update(chunk)
    return sha.hexdigest()

# --- DOWNLOAD LOOP ---
for m in range(1, 13):
    month = f"{m:02d}"
    file_name = f"yellow_tripdata_{YEAR}-{month}.parquet"
    url = f"{BASE_URL}/{file_name}"
    dest_path = os.path.join(DEST_DIR, file_name)

    if os.path.exists(dest_path):
        print(f"✔ File already exists: {file_name}")
        continue

    print(f"⬇ Downloading {file_name} ...")
    with requests.get(url, stream=True) as r:
        r.raise_for_status()
        with open(dest_path, "wb") as f:
            for chunk in tqdm(r.iter_content(chunk_size=8192), desc=file_name):
                if chunk:
                    f.write(chunk)

    checksum = sha256_checksum(dest_path)
    print(f"✔ Completed {file_name}, SHA256: {checksum}")

    # --- quick validation read ---
    try:
        df_sample = pd.read_parquet(dest_path, engine="pyarrow", columns=["tpep_pickup_datetime"])
        print(f"Sample rows: {len(df_sample)}\n")
    except Exception as e:
        print(f"⚠ Could not read sample from {file_name}: {e}")

⬇ Downloading yellow_tripdata_2024-01.parquet ...

yellow_tripdata_2024-01.parquet: 6099it [00:00, 6418.86it/s]

✔ Completed yellow_tripdata_2024-01.parquet, SHA256: c4d59da7bbc8abaeeeb1727947ee93d9891a71acb42854bd80db1571b2030510
⚠ Could not read sample from yellow_tripdata_2024-01.parquet: A type extension with name pandas.period already defined
⬇ Downloading yellow_tripdata_2024-02.parquet ...

yellow_tripdata_2024-02.parquet: 6147it [00:00, 6607.00it/s]

✔ Completed yellow_tripdata_2024-02.parquet, SHA256: c76c43c18c6c6664080dd920baab4928988d5786a6b65980792ca7cd796f9f20
⚠ Could not read sample from yellow_tripdata_2024-02.parquet: A type extension with name pandas.period already defined
⬇ Downloading yellow_tripdata_2024-03.parquet ...

yellow_tripdata_2024-03.parquet: 7334it [00:01, 5893.43it/s]

✔ Completed yellow_tripdata_2024-03.parquet, SHA256: 2d4cdc8fb96726cdd3803b13b02d2e61e71d45720aff0ebc693a8bdd1f249823
⚠ Could not read sample from yellow_tripdata_2024-03.parquet: A type extension with name pandas.period already defined
⬇ Downloading yellow_tripdata_2024-04.parquet ...

yellow_tripdata_2024-04.parquet: 7219it [00:01, 5968.86it/s]

✔ Completed yellow_tripdata_2024-04.parquet, SHA256: ce37f736c7cf9e92164c850ef2b502a8f7bb590fc1804b6edbcb80293da01b89
⚠ Could not read sample from yellow_tripdata_2024-04.parquet: A type extension with name pandas.period already defined
⬇ Downloading yellow_tripdata_2024-05.parquet ...

yellow_tripdata_2024-05.parquet: 7636it [00:01, 5431.37it/s]

✔ Completed yellow_tripdata_2024-05.parquet, SHA256: 1974230be2b5a3ea92e47b5eb77f32dbf1de896d81ad8df4ab6faba52749ad23
⚠ Could not read sample from yellow_tripdata_2024-05.parquet: A type extension with name pandas.period already defined
⬇ Downloading yellow_tripdata_2024-06.parquet ...

yellow_tripdata_2024-06.parquet: 7308it [00:01, 6184.27it/s]

✔ Completed yellow_tripdata_2024-06.parquet, SHA256: 677cf14c8347f745b583f012fbdba072334c6c4efa17bfd6a64369f2ba30329c
⚠ Could not read sample from yellow_tripdata_2024-06.parquet: A type extension with name pandas.period already defined
⬇ Downloading yellow_tripdata_2024-07.parquet ...

yellow_tripdata_2024-07.parquet: 6385it [00:01, 4225.46it/s]

✔ Completed yellow_tripdata_2024-07.parquet, SHA256: af12d6b04daeb78550799ae99933d495b27d715b6dbb0fad9bb750a4537d3070
⚠ Could not read sample from yellow_tripdata_2024-07.parquet: A type extension with name pandas.period already defined
⬇ Downloading yellow_tripdata_2024-08.parquet ...

yellow_tripdata_2024-08.parquet: 6234it [00:01, 5332.20it/s]

✔ Completed yellow_tripdata_2024-08.parquet, SHA256: 7315643dd16bafc03e27d9903edbfd35404c2550a695d0da0a3e73852d940cfb
⚠ Could not read sample from yellow_tripdata_2024-08.parquet: A type extension with name pandas.period already defined
⬇ Downloading yellow_tripdata_2024-09.parquet ...

yellow_tripdata_2024-09.parquet: 7468it [00:01, 6298.40it/s]

✔ Completed yellow_tripdata_2024-09.parquet, SHA256: 2f42e4a383a6635de803001462848d0aee2b47f6ce899126805d2d05361fb843
⚠ Could not read sample from yellow_tripdata_2024-09.parquet: A type extension with name pandas.period already defined
⬇ Downloading yellow_tripdata_2024-10.parquet ...

yellow_tripdata_2024-10.parquet: 7855it [00:01, 6318.97it/s]

✔ Completed yellow_tripdata_2024-10.parquet, SHA256: d19fe05aa0b259af24eb47051735293287f1e6dc263ba04030ec1ab4c6ec2650
⚠ Could not read sample from yellow_tripdata_2024-10.parquet: A type extension with name pandas.period already defined
⬇ Downloading yellow_tripdata_2024-11.parquet ...

yellow_tripdata_2024-11.parquet: 7405it [00:01, 6184.92it/s]

✔ Completed yellow_tripdata_2024-11.parquet, SHA256: 5ef321876de5007a7c147a347389133fc94fd7ac28f82eb1d57d8f2cf05cfd3b
⚠ Could not read sample from yellow_tripdata_2024-11.parquet: A type extension with name pandas.period already defined
⬇ Downloading yellow_tripdata_2024-12.parquet ...

yellow_tripdata_2024-12.parquet: 7511it [00:01, 5971.95it/s]

✔ Completed yellow_tripdata_2024-12.parquet, SHA256: 41ebf7db80bebde60c58e5143c14cdf38ad04a0f3e3ff44215b3e240d55f6c78
⚠ Could not read sample from yellow_tripdata_2024-12.parquet: A type extension with name pandas.period already defined

In [4]:
import os, pandas as pd
from io import StringIO

TLC_PATH = r"X:\data\raw\tlc\2024"

records = [
    {"File": f, "Size_MB": round(os.path.getsize(os.path.join(TLC_PATH, f))/1_000_000,2)}
    for f in sorted(os.listdir(TLC_PATH)) if f.endswith(".parquet")
]
df = pd.DataFrame(records)

# build markdown text
text = StringIO()
text.write("# Methodology – Data Sources & Merge Logic\n\n")
text.write("### TLC Data Verification (Local Copy)\n\n")
text.write(df.to_markdown(index=False))
text.write(f"\n\nTotal files: {len(df)} | Combined size: {round(df['Size_MB'].sum(),2)} MB\n")

# overwrite the file completely
with open(r"..\docs\methodology.md", "w", encoding="utf-8", newline="\n") as f:
    f.write(text.getvalue())

print("✅ methodology.md rebuilt cleanly as UTF-8.")

df_files = pd.DataFrame(records)
display(df_files)

# Quick summary
total_size = round(df_files["Size_MB"].sum(), 2)
print(f"\nTotal files: {len(df_files)} | Combined size: {total_size} MB")

✅ methodology.md rebuilt cleanly as UTF-8.

                               File  Size_MB
0   yellow_tripdata_2024-01.parquet    49.96
1   yellow_tripdata_2024-02.parquet    50.35
2   yellow_tripdata_2024-03.parquet    60.08
3   yellow_tripdata_2024-04.parquet    59.13
4   yellow_tripdata_2024-05.parquet    62.55
5   yellow_tripdata_2024-06.parquet    59.86
6   yellow_tripdata_2024-07.parquet    52.30
7   yellow_tripdata_2024-08.parquet    51.07
8   yellow_tripdata_2024-09.parquet    61.17
9   yellow_tripdata_2024-10.parquet    64.35
10  yellow_tripdata_2024-11.parquet    60.66
11  yellow_tripdata_2024-12.parquet    61.52

Total files: 12 | Combined size: 693.0 MB

## NOAA 2024 Weather Data Ingestion & City-wide Hourly Aggregation

In [3]:
# --- NOAA WEATHER DATA INGESTION PLAN ---

import os, hashlib, requests
from tqdm import tqdm

BASE_INDEX = "https://www.ncei.noaa.gov/data/local-climatological-data/access/2024"
DEST_DIR = r"X:\data\raw\noaa\2024"
os.makedirs(DEST_DIR, exist_ok=True)

# Map human-friendly station names to the correct USAF-WBAN filenames
STATIONS = {
    "JFK":        "72501504789.csv",
    "LaGuardia":  "72503014732.csv",
    "CentralPark":"72505394728.csv",
    "Newark":     "72502014734.csv",
    "Teterboro":  "72502594741.csv",
}

def sha256_checksum(file_path, chunk_size=1024 * 1024):
    sha = hashlib.sha256()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(chunk_size), b""):
            sha.update(chunk)
    return sha.hexdigest()

for name, fname in STATIONS.items():
    url = f"{BASE_INDEX}/{fname}"
    dest_path = os.path.join(DEST_DIR, f"station_{name}_2024.csv")

    if os.path.exists(dest_path) and os.path.getsize(dest_path) > 0:
        print(f"✔ {name}: already exists ({dest_path})")
        continue

    print(f"⬇ Downloading {name} → {fname}")
    try:
        with requests.get(url, stream=True, timeout=60) as r:
            r.raise_for_status()
            with open(dest_path, "wb") as f:
                for chunk in tqdm(r.iter_content(chunk_size=1024 * 1024), desc=name):
                    if chunk:
                        f.write(chunk)
    except requests.HTTPError as e:
        print(f"❌ HTTP error for {name} ({url}): {e}")
        if os.path.exists(dest_path):
            os.remove(dest_path)
        continue
    except Exception as e:
        print(f"❌ Error for {name}: {e}")
        if os.path.exists(dest_path):
            os.remove(dest_path)
        continue

    # checksum
    checksum = sha256_checksum(dest_path)
    size_mb = round(os.path.getsize(dest_path) / (1024 * 1024), 2)
    print(f"✔ {name}: downloaded {size_mb} MB, SHA256={checksum}")

✔ JFK: already exists (X:\data\raw\noaa\2024\station_JFK_2024.csv)
✔ LaGuardia: already exists (X:\data\raw\noaa\2024\station_LaGuardia_2024.csv)
✔ CentralPark: already exists (X:\data\raw\noaa\2024\station_CentralPark_2024.csv)
✔ Newark: already exists (X:\data\raw\noaa\2024\station_Newark_2024.csv)
✔ Teterboro: already exists (X:\data\raw\noaa\2024\station_Teterboro_2024.csv)

In [ ]:
import os
import pandas as pd
import numpy as np
from datetime import datetime
from statistics import mode
from tqdm import tqdm
import pyarrow
from pathlib import Path
import shutil, time

RAW_PATH = r"X:\data\raw\noaa\2024"
# Primary (X:) plus local canonical output in repo
OUT_PRIMARY = r"X:\data\interim\noaa_hourly_citywide_2024.parquet"
OUT_LOCAL = os.path.abspath(os.path.join("..", "data", "interim", "noaa_hourly_citywide_2024.parquet"))

# Ensure local directory exists
os.makedirs(os.path.dirname(OUT_LOCAL), exist_ok=True)

STATIONS = {
    "JFK":        "station_JFK_2024.csv",
    "LaGuardia":  "station_LaGuardia_2024.csv",
    "CentralPark":"station_CentralPark_2024.csv",
    "Newark":     "station_Newark_2024.csv",
    "Teterboro":  "station_Teterboro_2024.csv",
}

COLS = [
    "DATE",
    "HourlyDryBulbTemperature",
    "HourlyRelativeHumidity",
    "HourlyWindSpeed",
    "HourlyPrecipitation",
    "HourlyVisibility",
    "HourlyPresentWeatherType"
]

def safe_mode(series):
    try:
        vals = series.dropna()
        return mode(vals) if len(vals) else np.nan
    except Exception:
        return np.nan

def clean_noaa_csv(path):
    df = pd.read_csv(path, usecols=lambda c: c in COLS, low_memory=False)
    # --- safer datetime handling around DST ---
    df["DATE"] = pd.to_datetime(df["DATE"], errors="coerce", utc=True)
    # Convert to local tz; floor to hour with DST rules, then drop tz
    df["DATE"] = (
        df["DATE"]
        .dt.tz_convert("America/New_York")
        .dt.floor("h", ambiguous="NaT", nonexistent="shift_forward")
        .dt.tz_localize(None)
    )
    # Numeric conversions
    num_cols = [
        "HourlyDryBulbTemperature",
        "HourlyRelativeHumidity",
        "HourlyWindSpeed",
        "HourlyPrecipitation",
        "HourlyVisibility"
    ]
    for c in num_cols:
        df[c] = pd.to_numeric(df[c], errors="coerce")

    df["Station"] = os.path.basename(path).split("_")[1]

    agg = (
        df
        .groupby(["Station", "DATE"], dropna=True)
        .agg({
            "HourlyDryBulbTemperature": "mean",
            "HourlyRelativeHumidity": "mean",
            "HourlyWindSpeed": "mean",
            "HourlyPrecipitation": "sum",
            "HourlyVisibility": "mean",
            "HourlyPresentWeatherType": safe_mode
        })
        .reset_index()
        .rename(columns={
            "DATE": "observation_hour_local",
            "HourlyDryBulbTemperature": "temp_c",
            "HourlyRelativeHumidity": "rh_percent",
            "HourlyWindSpeed": "wind_ms",
            "HourlyPrecipitation": "precip_mm",
            "HourlyVisibility": "visibility_km",
            "HourlyPresentWeatherType": "weather_code"
        })
    )
    return agg

# === PROCESS ALL STATIONS ===
frames = []
for name, fname in tqdm(STATIONS.items(), desc="Processing stations"):
    fpath = os.path.join(RAW_PATH, fname)
    if not os.path.exists(fpath):
        print(f"⚠ Missing file: {fpath}")
        continue
    frames.append(clean_noaa_csv(fpath))

if not frames:
    raise RuntimeError("No station files were found. Check RAW_PATH and filenames.")

df_all = pd.concat(frames, ignore_index=True)
print(f"Combined hourly rows (all stations): {len(df_all):,}")

# === CITYWIDE AGGREGATION ===
agg_city = (
    df_all
    .groupby("observation_hour_local", dropna=True)
    .agg({
        "temp_c": "mean",
        "rh_percent": "mean",
        "wind_ms": "mean",
        "precip_mm": "sum",
        "visibility_km": "mean",
        "weather_code": safe_mode
    })
    .reset_index()
)

agg_city = agg_city.sort_values("observation_hour_local").reset_index(drop=True)
print(f"Citywide hourly records: {len(agg_city):,}")

# --- canonical write locally first ---
agg_city.to_parquet(OUT_LOCAL, index=False)
print(f"✅ Saved local canonical file to: {OUT_LOCAL}")

# --- then attempt copy to X: with retries (optional) ---
def copy_with_retries(src, dst, retries=3, delay=2.0):
    for i in range(1, retries+1):
        try:
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copy2(src, dst)
            print(f"📤 Copied to X: {dst}")
            return True
        except PermissionError as e:
            print(f"Attempt {i}/{retries}: PermissionError copying to {dst}: {e}")
        except Exception as e:
            print(f"Attempt {i}/{retries}: Error copying to {dst}: {e}")
        time.sleep(delay)
    return False

_ = copy_with_retries(OUT_LOCAL, OUT_PRIMARY)

Processing stations: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]

Combined hourly rows (all stations): 43,825
Citywide hourly records: 8,782
⚠ Permission denied for X:\data\interim\noaa_hourly_citywide_2024.parquet: [Errno 13] Permission denied: 'X:\\data\\interim\\noaa_hourly_citywide_2024.parquet'
✅ Saved aggregated file to: c:\Users\juraj.madzunkov\Documents\C\DA\CA1\data\interim\noaa_hourly_citywide_2024.parquet
Citywide hourly records: 8,782
⚠ Permission denied for X:\data\interim\noaa_hourly_citywide_2024.parquet: [Errno 13] Permission denied: 'X:\\data\\interim\\noaa_hourly_citywide_2024.parquet'
✅ Saved aggregated file to: c:\Users\juraj.madzunkov\Documents\C\DA\CA1\data\interim\noaa_hourly_citywide_2024.parquet

In [9]:
# Check X: drive write capability
import os, time, shutil
from pathlib import Path

x_dir = r"X:\\data\\interim"
print(f"Target directory: {x_dir}")
print(f"Exists: {os.path.exists(x_dir)} | IsDir: {os.path.isdir(x_dir)}")
try:
    os.makedirs(x_dir, exist_ok=True)
    print("mkdir ok (or already existed)")
except Exception as e:
    print(f"mkdir failed: {e}")

print("Access flags:")
print(f"  R_OK={os.access(x_dir, os.R_OK)} W_OK={os.access(x_dir, os.W_OK)} X_OK={os.access(x_dir, os.X_OK)}")

# disk usage (best effort)
try:
    usage = shutil.disk_usage("X:\\")
    print(f"Disk usage X: total={usage.total//(1024**3)}GB free={usage.free//(1024**3)}GB")
except Exception as e:
    print(f"disk_usage failed: {e}")

# write test
test_path = os.path.join(x_dir, f"__write_test_{int(time.time())}.tmp")
try:
    with open(test_path, "wb") as f:
        f.write(b"test")
        f.flush()
        os.fsync(f.fileno())
    print(f"Write test: success -> {test_path}")
    os.remove(test_path)
    print("Cleanup: removed temp file")
except Exception as e:
    print(f"Write test: FAILED -> {e}")

Target directory: X:\\data\\interim
Exists: True | IsDir: True
mkdir ok (or already existed)
Access flags:
  R_OK=True W_OK=True X_OK=True
Disk usage X: total=1048576GB free=1048576GB
Write test: success -> X:\\data\\interim\__write_test_1761333615.tmp
Cleanup: removed temp file

In [12]:
# Helper: copy parquet to X: with retries
import os, time, shutil

def copy_with_retries(src, dst, retries=3, delay=2.0):
    for i in range(1, retries+1):
        try:
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copy2(src, dst)
            print(f"Copy success -> {dst}")
            return True
        except PermissionError as e:
            print(f"Attempt {i}/{retries}: PermissionError copying to {dst}: {e}")
        except Exception as e:
            print(f"Attempt {i}/{retries}: Error copying to {dst}: {e}")
        time.sleep(delay)
    return False

In [13]:
# Try copying the locally saved NOAA parquet to X: (no recompute)
import os
src = os.path.abspath(os.path.join("..", "data", "interim", "noaa_hourly_citywide_2024.parquet"))
dst = r"X:\\data\\interim\\noaa_hourly_citywide_2024.parquet"
print(f"Source exists: {os.path.exists(src)} -> {src}")
print(f"Dest path: {dst}")

# More robust copy: remove dest if locked/readonly may still fail
if os.path.exists(dst):
    try:
        os.remove(dst)
        print("Removed existing destination file to avoid lock/readonly issues")
    except Exception as e:
        print(f"Could not remove existing destination: {e}")

copied = copy_with_retries(src, dst, retries=5, delay=2.5)
print(f"Copy result: {copied}")

Source exists: True -> c:\Users\juraj.madzunkov\Documents\C\DA\CA1\data\interim\noaa_hourly_citywide_2024.parquet
Dest path: X:\\data\\interim\\noaa_hourly_citywide_2024.parquet
Copy success -> X:\\data\\interim\\noaa_hourly_citywide_2024.parquet
Copy result: True

## Data validation

In [14]:
# Verify sizes and checksums for local vs X: parquet
import os, hashlib

local_pq = os.path.abspath(os.path.join("..", "data", "interim", "noaa_hourly_citywide_2024.parquet"))
x_pq = r"X:\\data\\interim\\noaa_hourly_citywide_2024.parquet"

print("Local:")
print(f"  path: {local_pq}")
print(f"  exists: {os.path.exists(local_pq)} size: {os.path.getsize(local_pq) if os.path.exists(local_pq) else 'N/A'} bytes")

print("X drive:")
print(f"  path: {x_pq}")
print(f"  exists: {os.path.exists(x_pq)} size: {os.path.getsize(x_pq) if os.path.exists(x_pq) else 'N/A'} bytes")

def sha256(path):
    h=hashlib.sha256()
    with open(path,'rb') as f:
        for chunk in iter(lambda: f.read(1<<20), b''):
            h.update(chunk)
    return h.hexdigest()

if os.path.exists(local_pq) and os.path.exists(x_pq):
    h_local = sha256(local_pq)
    h_x = sha256(x_pq)
    print(f"SHA256 local: {h_local}")
    print(f"SHA256 X:     {h_x}")
    print(f"Equal: {h_local == h_x}")

Local:
  path: c:\Users\juraj.madzunkov\Documents\C\DA\CA1\data\interim\noaa_hourly_citywide_2024.parquet
  exists: True size: 156322 bytes
X drive:
  path: X:\\data\\interim\\noaa_hourly_citywide_2024.parquet
  exists: True size: 156322 bytes
SHA256 local: 922c9a510d5be4a36f29d4570b348b07032bf55cf3d23cbd9fae69af190db1e3
SHA256 X:     922c9a510d5be4a36f29d4570b348b07032bf55cf3d23cbd9fae69af190db1e3
Equal: True

In [15]:
# Read agg parquet and validate structure and content
import pandas as pd, numpy as np
import os

local_pq = os.path.abspath(os.path.join("..", "data", "interim", "noaa_hourly_citywide_2024.parquet"))
df = pd.read_parquet(local_pq, engine="pyarrow")

print(df.shape)
print(df.dtypes)
print("min/max observation_hour_local:", df["observation_hour_local"].min(), df["observation_hour_local"].max())
print("nulls per column:\n", df.isna().sum())

# duplicates check on hour label
dup_counts = df["observation_hour_local"].value_counts()
dups = dup_counts[dup_counts>1]
print(f"duplicate hour labels: {len(dups)}")
if len(dups):
    print(dups.head())

print("head:")
print(df.head(3))
print("tail:")
print(df.tail(3))

(8782, 7)
observation_hour_local    datetime64[ns]
temp_c                           float64
rh_percent                       float64
wind_ms                          float64
precip_mm                        float64
visibility_km                    float64
weather_code                      object
dtype: object
min/max observation_hour_local: 2023-12-31 19:00:00 2024-12-31 18:00:00
nulls per column:
 observation_hour_local       0
temp_c                       0
rh_percent                   0
wind_ms                      0
precip_mm                    0
visibility_km                0
weather_code              6466
dtype: int64
duplicate hour labels: 0
head:
  observation_hour_local  temp_c  rh_percent  wind_ms  precip_mm  \
0    2023-12-31 19:00:00    40.4        63.0      5.4        0.0
1    2023-12-31 20:00:00    40.0        64.0      5.2        0.0
2    2023-12-31 21:00:00    39.4        67.0      5.0        0.0

   visibility_km    weather_code
0         10.000  -RA:02 |RA |RA
1          9.988            None
2         10.000            None
tail:
     observation_hour_local     temp_c  rh_percent    wind_ms  precip_mm  \
8779    2024-12-31 16:00:00  44.133333   83.786667  10.063333       2.14
8780    2024-12-31 17:00:00  43.866667   88.760000  11.360000       3.23
8781    2024-12-31 18:00:00  44.650000   89.600000   9.033333       0.07

      visibility_km         weather_code
8779       5.220000                |TS |
8780       3.263000  +RA:02 BR:1 |RA |RA
8781       8.933333   RA:02 BR:1 |RA |RA

In [16]:
# Coverage vs expected 2024 hours in America/New_York
import pandas as pd
from datetime import datetime

local_pq = os.path.abspath(os.path.join("..", "data", "interim", "noaa_hourly_citywide_2024.parquet"))
df = pd.read_parquet(local_pq, engine="pyarrow")

# Build expected hourly labels in local time, then drop tz to match df
rng = pd.date_range("2024-01-01 00:00", "2025-01-01 00:00", freq="H", tz="America/New_York", inclusive="left")
rng_naive = rng.tz_localize(None)

actual_hours = set(df["observation_hour_local"].astype("datetime64[ns]").tolist())
expected_hours = set(rng_naive.tolist())

missing = sorted(list(expected_hours - actual_hours))
extra = sorted(list(actual_hours - expected_hours))

print(f"Expected hours: {len(expected_hours)} | Actual: {len(actual_hours)}")
print(f"Missing hours: {len(missing)} | Extra hours (labels not in expected): {len(extra)}")
if missing[:5]:
    print("First 5 missing:", missing[:5])
if extra[:5]:
    print("First 5 extras:", extra[:5])

Expected hours: 8783 | Actual: 8782
Missing hours: 6 | Extra hours (labels not in expected): 5
First 5 missing: [Timestamp('2024-11-03 01:00:00'), Timestamp('2024-12-31 19:00:00'), Timestamp('2024-12-31 20:00:00'), Timestamp('2024-12-31 21:00:00'), Timestamp('2024-12-31 22:00:00')]
First 5 extras: [Timestamp('2023-12-31 19:00:00'), Timestamp('2023-12-31 20:00:00'), Timestamp('2023-12-31 21:00:00'), Timestamp('2023-12-31 22:00:00'), Timestamp('2023-12-31 23:00:00')]

C:\Users\juraj.madzunkov\AppData\Local\Temp\ipykernel_45564\2061928038.py:9: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  rng = pd.date_range("2024-01-01 00:00", "2025-01-01 00:00", freq="H", tz="America/New_York", inclusive="left")

In [18]:
# Raw → Aggregation → Compare with saved parquet
import os
import pandas as pd
import numpy as np
from statistics import mode

RAW_PATH_VERIFY = r"X:\\data\\raw\\noaa\\2024"
STATIONS_VERIFY = {
    "JFK":        "station_JFK_2024.csv",
    "LaGuardia":  "station_LaGuardia_2024.csv",
    "CentralPark":"station_CentralPark_2024.csv",
    "Newark":     "station_Newark_2024.csv",
    "Teterboro":  "station_Teterboro_2024.csv",
}
COLS_V = [
    "DATE",
    "HourlyDryBulbTemperature",
    "HourlyRelativeHumidity",
    "HourlyWindSpeed",
    "HourlyPrecipitation",
    "HourlyVisibility",
    "HourlyPresentWeatherType",
]

def safe_mode(series):
    try:
        vals = series.dropna()
        return mode(vals) if len(vals) else np.nan
    except Exception:
        return np.nan

# station-level clean/aggregate (same as production)
def clean_noaa_csv_verify(path):
    df = pd.read_csv(path, usecols=lambda c: c in COLS_V, low_memory=False)
    df["DATE"] = pd.to_datetime(df["DATE"], errors="coerce", utc=True)
    df["DATE"] = (
        df["DATE"].dt.tz_convert("America/New_York").dt.floor("h", ambiguous="NaT", nonexistent="shift_forward").dt.tz_localize(None)
    )
    for c in [
        "HourlyDryBulbTemperature",
        "HourlyRelativeHumidity",
        "HourlyWindSpeed",
        "HourlyPrecipitation",
        "HourlyVisibility",
    ]:
        df[c] = pd.to_numeric(df[c], errors="coerce")
    df["Station"] = os.path.basename(path).split("_")[1]
    agg = (
        df.groupby(["Station","DATE"], dropna=True)
          .agg({
              "HourlyDryBulbTemperature":"mean",
              "HourlyRelativeHumidity":"mean",
              "HourlyWindSpeed":"mean",
              "HourlyPrecipitation":"sum",
              "HourlyVisibility":"mean",
              "HourlyPresentWeatherType": safe_mode
          })
          .reset_index()
          .rename(columns={
              "DATE":"observation_hour_local",
              "HourlyDryBulbTemperature":"temp_c",
              "HourlyRelativeHumidity":"rh_percent",
              "HourlyWindSpeed":"wind_ms",
              "HourlyPrecipitation":"precip_mm",
              "HourlyVisibility":"visibility_km",
              "HourlyPresentWeatherType":"weather_code",
          })
    )
    return agg

frames=[]
for name,fname in STATIONS_VERIFY.items():
    p=os.path.join(RAW_PATH_VERIFY,fname)
    if not os.path.exists(p):
        print(f"Missing raw file: {p}")
        continue
    frames.append(clean_noaa_csv_verify(p))

ver_all = pd.concat(frames, ignore_index=True)
ver_city = (
    ver_all.groupby("observation_hour_local", dropna=True)
           .agg({
               "temp_c":"mean",
               "rh_percent":"mean",
               "wind_ms":"mean",
               "precip_mm":"sum",
               "visibility_km":"mean",
               "weather_code": safe_mode,
           })
           .reset_index()
           .sort_values("observation_hour_local")
           .reset_index(drop=True)
)

# Load saved parquet and align for comparison
local_pq = os.path.abspath(os.path.join("..","data","interim","noaa_hourly_citywide_2024.parquet"))
saved = pd.read_parquet(local_pq, engine="pyarrow").sort_values("observation_hour_local").reset_index(drop=True)

print("Shapes -> computed:", ver_city.shape, " saved:", saved.shape)

# Compare time labels
same_hours = ver_city["observation_hour_local"].equals(saved["observation_hour_local"])
print("Hour labels identical:", same_hours)

# Numeric diffs
numeric_cols=["temp_c","rh_percent","wind_ms","precip_mm","visibility_km"]
diffs={}
for c in numeric_cols:
    a=ver_city[c].to_numpy()
    b=saved[c].to_numpy()
    if len(a)==len(b):
        diffs[c] = float(np.nanmax(np.abs(a-b)))
    else:
        diffs[c] = np.nan
print("Max abs diff per column:", diffs)

# Weather code equality (string)
wc_equal = ver_city["weather_code"].fillna("").equals(saved["weather_code"].fillna(""))
print("Weather code identical:", wc_equal)

ok = same_hours and wc_equal and all((np.isnan(v) or v<1e-9) for v in diffs.values())
print("Verification PASSED:", ok)

Shapes -> computed: (8782, 7)  saved: (8782, 7)
Hour labels identical: True
Max abs diff per column: {'temp_c': 0.0, 'rh_percent': 0.0, 'wind_ms': 0.0, 'precip_mm': 0.0, 'visibility_km': 0.0}
Weather code identical: True
Verification PASSED: True

In [19]:
# Storage size comparison (raw CSVs vs merged parquet)
import os
from pathlib import Path

raw_dir = Path(r"X:\\data\\raw\\noaa\\2024")
parquet_local = Path(os.path.abspath(os.path.join("..","data","interim","noaa_hourly_citywide_2024.parquet")))

raw_total = 0
for p in sorted(raw_dir.glob("station_*_2024.csv")):
    sz = p.stat().st_size
    raw_total += sz
    print(f"{p.name:32} {sz/1_000_000:8.2f} MB")

pq_size = parquet_local.stat().st_size
print("\nTotals:")
print(f"Raw CSV total:     {raw_total/1_000_000:.2f} MB")
print(f"Merged Parquet:    {pq_size/1_000_000:.2f} MB")
if raw_total>0:
    print(f"Compression ratio: {raw_total/pq_size:,.1f}x smaller")

print("\nWhy so small?")
print("- Aggregation: 43k+ station-hour rows → 8.8k city-hour rows")
print("- Fewer columns: we keep 6 numeric + 1 categorical")
print("- Parquet compression + encoding (dictionary/bit packing) is efficient for floats and sparse strings")

station_CentralPark_2024.csv         8.53 MB
station_JFK_2024.csv                 8.09 MB
station_LaGuardia_2024.csv           8.58 MB
station_Newark_2024.csv              9.47 MB
station_Teterboro_2024.csv           6.95 MB

Totals:
Raw CSV total:     41.62 MB
Merged Parquet:    0.16 MB
Compression ratio: 266.3x smaller

Why so small?
- Aggregation: 43k+ station-hour rows → 8.8k city-hour rows
- Fewer columns: we keep 6 numeric + 1 categorical
- Parquet compression + encoding (dictionary/bit packing) is efficient for floats and sparse strings

In [20]:
# Peek: first 50 rows from merged parquet
import os, pandas as pd
from IPython.display import display

local_pq = os.path.abspath(os.path.join("..", "data", "interim", "noaa_hourly_citywide_2024.parquet"))
print(f"Reading: {local_pq}")
df_peek = pd.read_parquet(local_pq, engine="pyarrow")
print(f"Rows: {len(df_peek):,} | Columns: {list(df_peek.columns)}")
display(df_peek.head(50))

Reading: c:\Users\juraj.madzunkov\Documents\C\DA\CA1\data\interim\noaa_hourly_citywide_2024.parquet
Rows: 8,782 | Columns: ['observation_hour_local', 'temp_c', 'rh_percent', 'wind_ms', 'precip_mm', 'visibility_km', 'weather_code']

,observation_hour_local,temp_c,rh_percent,wind_ms,precip_mm,visibility_km,weather_code
0,2023-12-31 19:00:00,40.400000,63.000000,5.40,0.00,10.000,-RA:02 |RA |RA
1,2023-12-31 20:00:00,40.000000,64.000000,5.20,0.00,9.988,None
2,2023-12-31 21:00:00,39.400000,67.000000,5.00,0.00,10.000,None
3,2023-12-31 22:00:00,39.000000,69.200000,3.20,0.00,10.000,None
4,2023-12-31 23:00:00,38.300000,71.900000,2.10,0.00,9.988,None
5,2024-01-01 00:00:00,38.400000,73.800000,4.40,0.00,10.000,-RA:02 |RA |RA
6,2024-01-01 01:00:00,38.000000,78.200000,3.80,0.01,9.600,-RA:02 |RA |RA
7,2024-01-01 02:00:00,37.500000,82.850000,3.35,0.02,9.788,||RA
8,2024-01-01 03:00:00,38.400000,81.800000,2.80,0.01,10.000,-RA:02 |RA |RA
9,2024-01-01 04:00:00,40.200000,76.100000,3.30,0.00,10.000,None
10,2024-01-01 05:00:00,41.900000,70.700000,3.50,0.00,9.988,None
11,2024-01-01 06:00:00,43.533333,65.733333,3.20,0.00,10.000,None
12,2024-01-01 07:00:00,44.800000,58.600000,2.40,0.00,10.000,None
13,2024-01-01 08:00:00,44.700000,57.000000,2.60,0.00,9.988,None
14,2024-01-01 09:00:00,45.000000,55.800000,4.40,0.00,10.000,None
15,2024-01-01 10:00:00,44.200000,57.800000,6.40,0.00,10.000,None
16,2024-01-01 11:00:00,42.500000,59.800000,7.30,0.00,9.988,None
17,2024-01-01 12:00:00,40.800000,61.400000,6.60,0.00,10.000,None
18,2024-01-01 13:00:00,39.400000,62.800000,6.60,0.00,10.000,None
19,2024-01-01 14:00:00,38.600000,64.100000,6.40,0.00,9.988,None
20,2024-01-01 15:00:00,37.000000,65.200000,7.20,0.00,10.000,None
21,2024-01-01 16:00:00,36.000000,63.600000,6.60,0.00,10.000,None
22,2024-01-01 17:00:00,35.000000,67.000000,7.40,0.00,9.988,None
23,2024-01-01 18:00:00,32.600000,70.600000,6.20,0.00,10.000,None
24,2024-01-01 19:00:00,31.600000,73.200000,6.20,0.00,10.000,None
25,2024-01-01 20:00:00,30.600000,71.600000,4.70,0.00,9.988,None
26,2024-01-01 21:00:00,29.600000,70.800000,5.20,0.00,10.000,None
27,2024-01-01 22:00:00,28.800000,70.600000,6.00,0.00,10.000,None
28,2024-01-01 23:00:00,28.200000,70.000000,5.70,0.00,9.988,None
29,2024-01-02 00:00:00,27.600000,70.400000,6.00,0.00,10.000,None
30,2024-01-02 01:00:00,27.000000,72.200000,6.20,0.00,10.000,None
31,2024-01-02 02:00:00,27.600000,70.500000,5.40,0.00,9.988,None
32,2024-01-02 03:00:00,29.800000,66.400000,4.80,0.00,10.000,None
33,2024-01-02 04:00:00,32.400000,62.000000,6.00,0.00,10.000,None
34,2024-01-02 05:00:00,34.700000,56.800000,7.50,0.00,9.988,None
35,2024-01-02 06:00:00,38.200000,49.600000,7.00,0.00,10.000,None
36,2024-01-02 07:00:00,39.800000,47.000000,8.20,0.00,10.000,None
37,2024-01-02 08:00:00,41.100000,46.000000,6.50,0.00,9.988,None
38,2024-01-02 09:00:00,42.200000,43.400000,7.40,0.00,10.000,None
39,2024-01-02 10:00:00,42.200000,43.200000,7.80,0.00,10.000,None
40,2024-01-02 11:00:00,40.500000,47.200000,6.10,0.00,9.988,None
41,2024-01-02 12:00:00,39.600000,49.600000,4.60,0.00,10.000,None
42,2024-01-02 13:00:00,38.600000,52.600000,4.60,0.00,10.000,None
43,2024-01-02 14:00:00,37.200000,56.200000,5.80,0.00,9.988,None
44,2024-01-02 15:00:00,36.400000,57.200000,6.40,0.00,10.000,None
45,2024-01-02 16:00:00,35.600000,59.600000,7.00,0.00,10.000,None
46,2024-01-02 17:00:00,34.400000,62.500000,5.00,0.00,9.988,None
47,2024-01-02 18:00:00,33.800000,64.400000,6.40,0.00,10.000,None
48,2024-01-02 19:00:00,33.400000,67.600000,7.60,0.00,10.000,None
49,2024-01-02 20:00:00,33.500000,68.200000,6.10,0.00,9.988,None