## TLC 2024 data collection

This step downloads TLC 2024 monthly parquet files to X:, (X = to remote S3 type  of cloud storage - (iDrive E2)) skips existing files, and validates a sample column.

In [ ]:
import os, hashlib, requests
import pandas as pd
from tqdm import tqdm

# TLC Trip Data Downloader for 2024

BASE_URL = "https://d37ci6vzurychx.cloudfront.net/trip-data"
DEST_DIR = r"X:\data\raw\tlc\2024"
YEAR = "2024"

os.makedirs(DEST_DIR, exist_ok=True)

def sha256_checksum(file_path, chunk_size=8192):
    """Compute SHA256 checksum of a file."""
    sha = hashlib.sha256()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(chunk_size), b""):
            sha.update(chunk)
    return sha.hexdigest()

# --- DOWNLOAD LOOP ---
for m in range(1, 13):
    month = f"{m:02d}"
    file_name = f"yellow_tripdata_{YEAR}-{month}.parquet"
    url = f"{BASE_URL}/{file_name}"
    dest_path = os.path.join(DEST_DIR, file_name)

    if os.path.exists(dest_path):
        print(f"✔ File already exists: {file_name}")
        continue

    print(f"⬇ Downloading {file_name} ...")
    with requests.get(url, stream=True) as r:
        r.raise_for_status()
        with open(dest_path, "wb") as f:
            for chunk in tqdm(r.iter_content(chunk_size=8192), desc=file_name):
                if chunk:
                    f.write(chunk)

    checksum = sha256_checksum(dest_path)
    print(f"✔ Completed {file_name}, SHA256: {checksum}")

    # --- quick validation read ---
    try:
        df_sample = pd.read_parquet(dest_path, engine="pyarrow", columns=["tpep_pickup_datetime"])
        print(f"Sample rows: {len(df_sample)}\n")
    except Exception as e:
        print(f"⚠ Could not read sample from {file_name}: {e}")

⬇ Downloading yellow_tripdata_2024-01.parquet ...

yellow_tripdata_2024-01.parquet: 6099it [00:00, 6418.86it/s]

✔ Completed yellow_tripdata_2024-01.parquet, SHA256: c4d59da7bbc8abaeeeb1727947ee93d9891a71acb42854bd80db1571b2030510
⚠ Could not read sample from yellow_tripdata_2024-01.parquet: A type extension with name pandas.period already defined
⬇ Downloading yellow_tripdata_2024-02.parquet ...

yellow_tripdata_2024-02.parquet: 6147it [00:00, 6607.00it/s]

✔ Completed yellow_tripdata_2024-02.parquet, SHA256: c76c43c18c6c6664080dd920baab4928988d5786a6b65980792ca7cd796f9f20
⚠ Could not read sample from yellow_tripdata_2024-02.parquet: A type extension with name pandas.period already defined
⬇ Downloading yellow_tripdata_2024-03.parquet ...

yellow_tripdata_2024-03.parquet: 7334it [00:01, 5893.43it/s]

✔ Completed yellow_tripdata_2024-03.parquet, SHA256: 2d4cdc8fb96726cdd3803b13b02d2e61e71d45720aff0ebc693a8bdd1f249823
⚠ Could not read sample from yellow_tripdata_2024-03.parquet: A type extension with name pandas.period already defined
⬇ Downloading yellow_tripdata_2024-04.parquet ...

yellow_tripdata_2024-04.parquet: 7219it [00:01, 5968.86it/s]

✔ Completed yellow_tripdata_2024-04.parquet, SHA256: ce37f736c7cf9e92164c850ef2b502a8f7bb590fc1804b6edbcb80293da01b89
⚠ Could not read sample from yellow_tripdata_2024-04.parquet: A type extension with name pandas.period already defined
⬇ Downloading yellow_tripdata_2024-05.parquet ...

yellow_tripdata_2024-05.parquet: 7636it [00:01, 5431.37it/s]

✔ Completed yellow_tripdata_2024-05.parquet, SHA256: 1974230be2b5a3ea92e47b5eb77f32dbf1de896d81ad8df4ab6faba52749ad23
⚠ Could not read sample from yellow_tripdata_2024-05.parquet: A type extension with name pandas.period already defined
⬇ Downloading yellow_tripdata_2024-06.parquet ...

yellow_tripdata_2024-06.parquet: 7308it [00:01, 6184.27it/s]

✔ Completed yellow_tripdata_2024-06.parquet, SHA256: 677cf14c8347f745b583f012fbdba072334c6c4efa17bfd6a64369f2ba30329c
⚠ Could not read sample from yellow_tripdata_2024-06.parquet: A type extension with name pandas.period already defined
⬇ Downloading yellow_tripdata_2024-07.parquet ...

yellow_tripdata_2024-07.parquet: 6385it [00:01, 4225.46it/s]

✔ Completed yellow_tripdata_2024-07.parquet, SHA256: af12d6b04daeb78550799ae99933d495b27d715b6dbb0fad9bb750a4537d3070
⚠ Could not read sample from yellow_tripdata_2024-07.parquet: A type extension with name pandas.period already defined
⬇ Downloading yellow_tripdata_2024-08.parquet ...

yellow_tripdata_2024-08.parquet: 6234it [00:01, 5332.20it/s]

✔ Completed yellow_tripdata_2024-08.parquet, SHA256: 7315643dd16bafc03e27d9903edbfd35404c2550a695d0da0a3e73852d940cfb
⚠ Could not read sample from yellow_tripdata_2024-08.parquet: A type extension with name pandas.period already defined
⬇ Downloading yellow_tripdata_2024-09.parquet ...

yellow_tripdata_2024-09.parquet: 7468it [00:01, 6298.40it/s]

✔ Completed yellow_tripdata_2024-09.parquet, SHA256: 2f42e4a383a6635de803001462848d0aee2b47f6ce899126805d2d05361fb843
⚠ Could not read sample from yellow_tripdata_2024-09.parquet: A type extension with name pandas.period already defined
⬇ Downloading yellow_tripdata_2024-10.parquet ...

yellow_tripdata_2024-10.parquet: 7855it [00:01, 6318.97it/s]

✔ Completed yellow_tripdata_2024-10.parquet, SHA256: d19fe05aa0b259af24eb47051735293287f1e6dc263ba04030ec1ab4c6ec2650
⚠ Could not read sample from yellow_tripdata_2024-10.parquet: A type extension with name pandas.period already defined
⬇ Downloading yellow_tripdata_2024-11.parquet ...

yellow_tripdata_2024-11.parquet: 7405it [00:01, 6184.92it/s]

✔ Completed yellow_tripdata_2024-11.parquet, SHA256: 5ef321876de5007a7c147a347389133fc94fd7ac28f82eb1d57d8f2cf05cfd3b
⚠ Could not read sample from yellow_tripdata_2024-11.parquet: A type extension with name pandas.period already defined
⬇ Downloading yellow_tripdata_2024-12.parquet ...

yellow_tripdata_2024-12.parquet: 7511it [00:01, 5971.95it/s]

✔ Completed yellow_tripdata_2024-12.parquet, SHA256: 41ebf7db80bebde60c58e5143c14cdf38ad04a0f3e3ff44215b3e240d55f6c78
⚠ Could not read sample from yellow_tripdata_2024-12.parquet: A type extension with name pandas.period already defined

This cell summarizes downloaded TLC files, updates docs/methodology, and prints totals.

In [4]:
import os, pandas as pd
from io import StringIO

TLC_PATH = r"X:\data\raw\tlc\2024"

records = [
    {"File": f, "Size_MB": round(os.path.getsize(os.path.join(TLC_PATH, f))/1_000_000,2)}
    for f in sorted(os.listdir(TLC_PATH)) if f.endswith(".parquet")
]
df = pd.DataFrame(records)

# build markdown text
text = StringIO()
text.write("# Methodology – Data Sources & Merge Logic\n\n")
text.write("### TLC Data Verification (Local Copy)\n\n")
text.write(df.to_markdown(index=False))
text.write(f"\n\nTotal files: {len(df)} | Combined size: {round(df['Size_MB'].sum(),2)} MB\n")

# overwrite the file completely
with open(r"..\docs\methodology.md", "w", encoding="utf-8", newline="\n") as f:
    f.write(text.getvalue())

print("✅ methodology.md rebuilt cleanly as UTF-8.")

df_files = pd.DataFrame(records)
display(df_files)

# Quick summary
total_size = round(df_files["Size_MB"].sum(), 2)
print(f"\nTotal files: {len(df_files)} | Combined size: {total_size} MB")

✅ methodology.md rebuilt cleanly as UTF-8.

                               File  Size_MB
0   yellow_tripdata_2024-01.parquet    49.96
1   yellow_tripdata_2024-02.parquet    50.35
2   yellow_tripdata_2024-03.parquet    60.08
3   yellow_tripdata_2024-04.parquet    59.13
4   yellow_tripdata_2024-05.parquet    62.55
5   yellow_tripdata_2024-06.parquet    59.86
6   yellow_tripdata_2024-07.parquet    52.30
7   yellow_tripdata_2024-08.parquet    51.07
8   yellow_tripdata_2024-09.parquet    61.17
9   yellow_tripdata_2024-10.parquet    64.35
10  yellow_tripdata_2024-11.parquet    60.66
11  yellow_tripdata_2024-12.parquet    61.52

Total files: 12 | Combined size: 693.0 MB

## NOAA 2024 Weather Data Ingestion & City-wide Hourly Aggregation

This step downloads NOAA station CSVs for 2024:, computes checksums, and handles errors. Cleans station CSVs to NYC local hour, aggregates to citywide hourly metrics, writes locally, then copies to X:.

In [3]:
# --- NOAA WEATHER DATA INGESTION PLAN ---

import os, hashlib, requests
from tqdm import tqdm

BASE_INDEX = "https://www.ncei.noaa.gov/data/local-climatological-data/access/2024"
DEST_DIR = r"X:\data\raw\noaa\2024"
os.makedirs(DEST_DIR, exist_ok=True)

# Map human-friendly station names to the correct USAF-WBAN filenames
STATIONS = {
    "JFK":        "72501504789.csv",
    "LaGuardia":  "72503014732.csv",
    "CentralPark":"72505394728.csv",
    "Newark":     "72502014734.csv",
    "Teterboro":  "72502594741.csv",
}

def sha256_checksum(file_path, chunk_size=1024 * 1024):
    sha = hashlib.sha256()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(chunk_size), b""):
            sha.update(chunk)
    return sha.hexdigest()

for name, fname in STATIONS.items():
    url = f"{BASE_INDEX}/{fname}"
    dest_path = os.path.join(DEST_DIR, f"station_{name}_2024.csv")

    if os.path.exists(dest_path) and os.path.getsize(dest_path) > 0:
        print(f"✔ {name}: already exists ({dest_path})")
        continue

    print(f"⬇ Downloading {name} → {fname}")
    try:
        with requests.get(url, stream=True, timeout=60) as r:
            r.raise_for_status()
            with open(dest_path, "wb") as f:
                for chunk in tqdm(r.iter_content(chunk_size=1024 * 1024), desc=name):
                    if chunk:
                        f.write(chunk)
    except requests.HTTPError as e:
        print(f"❌ HTTP error for {name} ({url}): {e}")
        if os.path.exists(dest_path):
            os.remove(dest_path)
        continue
    except Exception as e:
        print(f"❌ Error for {name}: {e}")
        if os.path.exists(dest_path):
            os.remove(dest_path)
        continue

    # checksum
    checksum = sha256_checksum(dest_path)
    size_mb = round(os.path.getsize(dest_path) / (1024 * 1024), 2)
    print(f"✔ {name}: downloaded {size_mb} MB, SHA256={checksum}")

✔ JFK: already exists (X:\data\raw\noaa\2024\station_JFK_2024.csv)
✔ LaGuardia: already exists (X:\data\raw\noaa\2024\station_LaGuardia_2024.csv)
✔ CentralPark: already exists (X:\data\raw\noaa\2024\station_CentralPark_2024.csv)
✔ Newark: already exists (X:\data\raw\noaa\2024\station_Newark_2024.csv)
✔ Teterboro: already exists (X:\data\raw\noaa\2024\station_Teterboro_2024.csv)

This step probes X: drive write capability and disk info to diagnose network I/O issues.

In [ ]:
import os
import pandas as pd
import numpy as np
from datetime import datetime
from statistics import mode
from tqdm import tqdm
import pyarrow
from pathlib import Path
import shutil, time

RAW_PATH = r"X:\data\raw\noaa\2024"
# Primary (X:) plus local canonical output in repo
OUT_PRIMARY = r"X:\data\interim\noaa_hourly_citywide_2024.parquet"
OUT_LOCAL = os.path.abspath(os.path.join("..", "data", "interim", "noaa_hourly_citywide_2024.parquet"))

# Ensure local directory exists
os.makedirs(os.path.dirname(OUT_LOCAL), exist_ok=True)

STATIONS = {
    "JFK":        "station_JFK_2024.csv",
    "LaGuardia":  "station_LaGuardia_2024.csv",
    "CentralPark":"station_CentralPark_2024.csv",
    "Newark":     "station_Newark_2024.csv",
    "Teterboro":  "station_Teterboro_2024.csv",
}

COLS = [
    "DATE",
    "HourlyDryBulbTemperature",
    "HourlyRelativeHumidity",
    "HourlyWindSpeed",
    "HourlyPrecipitation",
    "HourlyVisibility",
    "HourlyPresentWeatherType"
]

def safe_mode(series):
    try:
        vals = series.dropna()
        return mode(vals) if len(vals) else np.nan
    except Exception:
        return np.nan

def clean_noaa_csv(path):
    df = pd.read_csv(path, usecols=lambda c: c in COLS, low_memory=False)
    # --- safer datetime handling around DST ---
    df["DATE"] = pd.to_datetime(df["DATE"], errors="coerce", utc=True)
    # Convert to local tz; floor to hour with DST rules, then drop tz
    df["DATE"] = (
        df["DATE"]
        .dt.tz_convert("America/New_York")
        .dt.floor("h", ambiguous="NaT", nonexistent="shift_forward")
        .dt.tz_localize(None)
    )
    # Numeric conversions
    num_cols = [
        "HourlyDryBulbTemperature",
        "HourlyRelativeHumidity",
        "HourlyWindSpeed",
        "HourlyPrecipitation",
        "HourlyVisibility"
    ]
    for c in num_cols:
        df[c] = pd.to_numeric(df[c], errors="coerce")

    df["Station"] = os.path.basename(path).split("_")[1]

    agg = (
        df
        .groupby(["Station", "DATE"], dropna=True)
        .agg({
            "HourlyDryBulbTemperature": "mean",
            "HourlyRelativeHumidity": "mean",
            "HourlyWindSpeed": "mean",
            "HourlyPrecipitation": "sum",
            "HourlyVisibility": "mean",
            "HourlyPresentWeatherType": safe_mode
        })
        .reset_index()
        .rename(columns={
            "DATE": "observation_hour_local",
            "HourlyDryBulbTemperature": "temp_c",
            "HourlyRelativeHumidity": "rh_percent",
            "HourlyWindSpeed": "wind_ms",
            "HourlyPrecipitation": "precip_mm",
            "HourlyVisibility": "visibility_km",
            "HourlyPresentWeatherType": "weather_code"
        })
    )
    return agg

# === PROCESS ALL STATIONS ===
frames = []
for name, fname in tqdm(STATIONS.items(), desc="Processing stations"):
    fpath = os.path.join(RAW_PATH, fname)
    if not os.path.exists(fpath):
        print(f"⚠ Missing file: {fpath}")
        continue
    frames.append(clean_noaa_csv(fpath))

if not frames:
    raise RuntimeError("No station files were found. Check RAW_PATH and filenames.")

df_all = pd.concat(frames, ignore_index=True)
print(f"Combined hourly rows (all stations): {len(df_all):,}")

# === CITYWIDE AGGREGATION ===
agg_city = (
    df_all
    .groupby("observation_hour_local", dropna=True)
    .agg({
        "temp_c": "mean",
        "rh_percent": "mean",
        "wind_ms": "mean",
        "precip_mm": "sum",
        "visibility_km": "mean",
        "weather_code": safe_mode
    })
    .reset_index()
)

agg_city = agg_city.sort_values("observation_hour_local").reset_index(drop=True)
print(f"Citywide hourly records: {len(agg_city):,}")

# --- canonical write locally first ---
agg_city.to_parquet(OUT_LOCAL, index=False)
print(f"✅ Saved local canonical file to: {OUT_LOCAL}")

# --- then attempt copy to X: with retries (optional) ---
def copy_with_retries(src, dst, retries=3, delay=2.0):
    for i in range(1, retries+1):
        try:
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copy2(src, dst)
            print(f"📤 Copied to X: {dst}")
            return True
        except PermissionError as e:
            print(f"Attempt {i}/{retries}: PermissionError copying to {dst}: {e}")
        except Exception as e:
            print(f"Attempt {i}/{retries}: Error copying to {dst}: {e}")
        time.sleep(delay)
    return False

_ = copy_with_retries(OUT_LOCAL, OUT_PRIMARY)

Processing stations: 100%|██████████| 5/5 [00:04<00:00,  1.01it/s]

Combined hourly rows (all stations): 43,825
Citywide hourly records: 8,782
⚠ Permission denied for X:\data\interim\noaa_hourly_citywide_2024.parquet: [Errno 13] Permission denied: 'X:\\data\\interim\\noaa_hourly_citywide_2024.parquet'
✅ Saved aggregated file to: c:\Users\juraj.madzunkov\Documents\C\DA\CA1\data\interim\noaa_hourly_citywide_2024.parquet
Citywide hourly records: 8,782
⚠ Permission denied for X:\data\interim\noaa_hourly_citywide_2024.parquet: [Errno 13] Permission denied: 'X:\\data\\interim\\noaa_hourly_citywide_2024.parquet'
✅ Saved aggregated file to: c:\Users\juraj.madzunkov\Documents\C\DA\CA1\data\interim\noaa_hourly_citywide_2024.parquet

In [9]:
# Check X: drive write capability
import os, time, shutil
from pathlib import Path

x_dir = r"X:\\data\\interim"
print(f"Target directory: {x_dir}")
print(f"Exists: {os.path.exists(x_dir)} | IsDir: {os.path.isdir(x_dir)}")
try:
    os.makedirs(x_dir, exist_ok=True)
    print("mkdir ok (or already existed)")
except Exception as e:
    print(f"mkdir failed: {e}")

print("Access flags:")
print(f"  R_OK={os.access(x_dir, os.R_OK)} W_OK={os.access(x_dir, os.W_OK)} X_OK={os.access(x_dir, os.X_OK)}")

# disk usage (best effort)
try:
    usage = shutil.disk_usage("X:\\")
    print(f"Disk usage X: total={usage.total//(1024**3)}GB free={usage.free//(1024**3)}GB")
except Exception as e:
    print(f"disk_usage failed: {e}")

# write test
test_path = os.path.join(x_dir, f"__write_test_{int(time.time())}.tmp")
try:
    with open(test_path, "wb") as f:
        f.write(b"test")
        f.flush()
        os.fsync(f.fileno())
    print(f"Write test: success -> {test_path}")
    os.remove(test_path)
    print("Cleanup: removed temp file")
except Exception as e:
    print(f"Write test: FAILED -> {e}")

Target directory: X:\\data\\interim
Exists: True | IsDir: True
mkdir ok (or already existed)
Access flags:
  R_OK=True W_OK=True X_OK=True
Disk usage X: total=1048576GB free=1048576GB
Write test: success -> X:\\data\\interim\__write_test_1761333615.tmp
Cleanup: removed temp file

This cell defines a copy_with_retries helper for robust network copies to X:.

In [12]:
# Helper: copy parquet to X: with retries
import os, time, shutil

def copy_with_retries(src, dst, retries=3, delay=2.0):
    for i in range(1, retries+1):
        try:
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copy2(src, dst)
            print(f"Copy success -> {dst}")
            return True
        except PermissionError as e:
            print(f"Attempt {i}/{retries}: PermissionError copying to {dst}: {e}")
        except Exception as e:
            print(f"Attempt {i}/{retries}: Error copying to {dst}: {e}")
        time.sleep(delay)
    return False

This cell copies the locally saved NOAA parquet to X: without recomputing; removes destination if needed.

In [13]:
# Try copying the locally saved NOAA parquet to X: (no recompute)
import os
src = os.path.abspath(os.path.join("..", "data", "interim", "noaa_hourly_citywide_2024.parquet"))
dst = r"X:\\data\\interim\\noaa_hourly_citywide_2024.parquet"
print(f"Source exists: {os.path.exists(src)} -> {src}")
print(f"Dest path: {dst}")

# More robust copy: remove dest if locked/readonly may still fail
if os.path.exists(dst):
    try:
        os.remove(dst)
        print("Removed existing destination file to avoid lock/readonly issues")
    except Exception as e:
        print(f"Could not remove existing destination: {e}")

copied = copy_with_retries(src, dst, retries=5, delay=2.5)
print(f"Copy result: {copied}")

Source exists: True -> c:\Users\juraj.madzunkov\Documents\C\DA\CA1\data\interim\noaa_hourly_citywide_2024.parquet
Dest path: X:\\data\\interim\\noaa_hourly_citywide_2024.parquet
Copy success -> X:\\data\\interim\\noaa_hourly_citywide_2024.parquet
Copy result: True

## Data validation

This section validates the NOAA aggregated parquet on X: and local: parity, structure, coverage, recomputation, and storage footprint.

This step verifies sizes and SHA256 parity for NOAA local vs X: parquet files.

In [14]:
# Verify sizes and checksums for local vs X: parquet
import os, hashlib

local_pq = os.path.abspath(os.path.join("..", "data", "interim", "noaa_hourly_citywide_2024.parquet"))
x_pq = r"X:\\data\\interim\\noaa_hourly_citywide_2024.parquet"

print("Local:")
print(f"  path: {local_pq}")
print(f"  exists: {os.path.exists(local_pq)} size: {os.path.getsize(local_pq) if os.path.exists(local_pq) else 'N/A'} bytes")

print("X drive:")
print(f"  path: {x_pq}")
print(f"  exists: {os.path.exists(x_pq)} size: {os.path.getsize(x_pq) if os.path.exists(x_pq) else 'N/A'} bytes")

def sha256(path):
    h=hashlib.sha256()
    with open(path,'rb') as f:
        for chunk in iter(lambda: f.read(1<<20), b''):
            h.update(chunk)
    return h.hexdigest()

if os.path.exists(local_pq) and os.path.exists(x_pq):
    h_local = sha256(local_pq)
    h_x = sha256(x_pq)
    print(f"SHA256 local: {h_local}")
    print(f"SHA256 X:     {h_x}")
    print(f"Equal: {h_local == h_x}")

Local:
  path: c:\Users\juraj.madzunkov\Documents\C\DA\CA1\data\interim\noaa_hourly_citywide_2024.parquet
  exists: True size: 156322 bytes
X drive:
  path: X:\\data\\interim\\noaa_hourly_citywide_2024.parquet
  exists: True size: 156322 bytes
SHA256 local: 922c9a510d5be4a36f29d4570b348b07032bf55cf3d23cbd9fae69af190db1e3
SHA256 X:     922c9a510d5be4a36f29d4570b348b07032bf55cf3d23cbd9fae69af190db1e3
Equal: True

This step reads the NOAA parquet, prints schema, min/max hour, null counts, and shows head/tail.

In [15]:
# Read agg parquet and validate structure and content
import pandas as pd, numpy as np
import os

local_pq = os.path.abspath(os.path.join("..", "data", "interim", "noaa_hourly_citywide_2024.parquet"))
df = pd.read_parquet(local_pq, engine="pyarrow")

print(df.shape)
print(df.dtypes)
print("min/max observation_hour_local:", df["observation_hour_local"].min(), df["observation_hour_local"].max())
print("nulls per column:\n", df.isna().sum())

# duplicates check on hour label
dup_counts = df["observation_hour_local"].value_counts()
dups = dup_counts[dup_counts>1]
print(f"duplicate hour labels: {len(dups)}")
if len(dups):
    print(dups.head())

print("head:")
print(df.head(3))
print("tail:")
print(df.tail(3))

(8782, 7)
observation_hour_local    datetime64[ns]
temp_c                           float64
rh_percent                       float64
wind_ms                          float64
precip_mm                        float64
visibility_km                    float64
weather_code                      object
dtype: object
min/max observation_hour_local: 2023-12-31 19:00:00 2024-12-31 18:00:00
nulls per column:
 observation_hour_local       0
temp_c                       0
rh_percent                   0
wind_ms                      0
precip_mm                    0
visibility_km                0
weather_code              6466
dtype: int64
duplicate hour labels: 0
head:
  observation_hour_local  temp_c  rh_percent  wind_ms  precip_mm  \
0    2023-12-31 19:00:00    40.4        63.0      5.4        0.0
1    2023-12-31 20:00:00    40.0        64.0      5.2        0.0
2    2023-12-31 21:00:00    39.4        67.0      5.0        0.0

   visibility_km    weather_code
0         10.000  -RA:02 |RA |RA
1          9.988            None
2         10.000            None
tail:
     observation_hour_local     temp_c  rh_percent    wind_ms  precip_mm  \
8779    2024-12-31 16:00:00  44.133333   83.786667  10.063333       2.14
8780    2024-12-31 17:00:00  43.866667   88.760000  11.360000       3.23
8781    2024-12-31 18:00:00  44.650000   89.600000   9.033333       0.07

      visibility_km         weather_code
8779       5.220000                |TS |
8780       3.263000  +RA:02 BR:1 |RA |RA
8781       8.933333   RA:02 BR:1 |RA |RA

This step compares NOAA hour labels to the expected 2024 America/New_York hourly range.

In [16]:
# Coverage vs expected 2024 hours in America/New_York
import pandas as pd
from datetime import datetime

local_pq = os.path.abspath(os.path.join("..", "data", "interim", "noaa_hourly_citywide_2024.parquet"))
df = pd.read_parquet(local_pq, engine="pyarrow")

# Build expected hourly labels in local time, then drop tz to match df
rng = pd.date_range("2024-01-01 00:00", "2025-01-01 00:00", freq="H", tz="America/New_York", inclusive="left")
rng_naive = rng.tz_localize(None)

actual_hours = set(df["observation_hour_local"].astype("datetime64[ns]").tolist())
expected_hours = set(rng_naive.tolist())

missing = sorted(list(expected_hours - actual_hours))
extra = sorted(list(actual_hours - expected_hours))

print(f"Expected hours: {len(expected_hours)} | Actual: {len(actual_hours)}")
print(f"Missing hours: {len(missing)} | Extra hours (labels not in expected): {len(extra)}")
if missing[:5]:
    print("First 5 missing:", missing[:5])
if extra[:5]:
    print("First 5 extras:", extra[:5])

Expected hours: 8783 | Actual: 8782
Missing hours: 6 | Extra hours (labels not in expected): 5
First 5 missing: [Timestamp('2024-11-03 01:00:00'), Timestamp('2024-12-31 19:00:00'), Timestamp('2024-12-31 20:00:00'), Timestamp('2024-12-31 21:00:00'), Timestamp('2024-12-31 22:00:00')]
First 5 extras: [Timestamp('2023-12-31 19:00:00'), Timestamp('2023-12-31 20:00:00'), Timestamp('2023-12-31 21:00:00'), Timestamp('2023-12-31 22:00:00'), Timestamp('2023-12-31 23:00:00')]

C:\Users\juraj.madzunkov\AppData\Local\Temp\ipykernel_45564\2061928038.py:9: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  rng = pd.date_range("2024-01-01 00:00", "2025-01-01 00:00", freq="H", tz="America/New_York", inclusive="left")

This step recomputes station→city aggregation from raw NOAA CSVs and compares results to the saved parquet for equivalence.

In [18]:
# Raw → Aggregation → Compare with saved parquet
import os
import pandas as pd
import numpy as np
from statistics import mode

RAW_PATH_VERIFY = r"X:\\data\\raw\\noaa\\2024"
STATIONS_VERIFY = {
    "JFK":        "station_JFK_2024.csv",
    "LaGuardia":  "station_LaGuardia_2024.csv",
    "CentralPark":"station_CentralPark_2024.csv",
    "Newark":     "station_Newark_2024.csv",
    "Teterboro":  "station_Teterboro_2024.csv",
}
COLS_V = [
    "DATE",
    "HourlyDryBulbTemperature",
    "HourlyRelativeHumidity",
    "HourlyWindSpeed",
    "HourlyPrecipitation",
    "HourlyVisibility",
    "HourlyPresentWeatherType",
]

def safe_mode(series):
    try:
        vals = series.dropna()
        return mode(vals) if len(vals) else np.nan
    except Exception:
        return np.nan

# station-level clean/aggregate (same as production)
def clean_noaa_csv_verify(path):
    df = pd.read_csv(path, usecols=lambda c: c in COLS_V, low_memory=False)
    df["DATE"] = pd.to_datetime(df["DATE"], errors="coerce", utc=True)
    df["DATE"] = (
        df["DATE"].dt.tz_convert("America/New_York").dt.floor("h", ambiguous="NaT", nonexistent="shift_forward").dt.tz_localize(None)
    )
    for c in [
        "HourlyDryBulbTemperature",
        "HourlyRelativeHumidity",
        "HourlyWindSpeed",
        "HourlyPrecipitation",
        "HourlyVisibility",
    ]:
        df[c] = pd.to_numeric(df[c], errors="coerce")
    df["Station"] = os.path.basename(path).split("_")[1]
    agg = (
        df.groupby(["Station","DATE"], dropna=True)
          .agg({
              "HourlyDryBulbTemperature":"mean",
              "HourlyRelativeHumidity":"mean",
              "HourlyWindSpeed":"mean",
              "HourlyPrecipitation":"sum",
              "HourlyVisibility":"mean",
              "HourlyPresentWeatherType": safe_mode
          })
          .reset_index()
          .rename(columns={
              "DATE":"observation_hour_local",
              "HourlyDryBulbTemperature":"temp_c",
              "HourlyRelativeHumidity":"rh_percent",
              "HourlyWindSpeed":"wind_ms",
              "HourlyPrecipitation":"precip_mm",
              "HourlyVisibility":"visibility_km",
              "HourlyPresentWeatherType":"weather_code",
          })
    )
    return agg

frames=[]
for name,fname in STATIONS_VERIFY.items():
    p=os.path.join(RAW_PATH_VERIFY,fname)
    if not os.path.exists(p):
        print(f"Missing raw file: {p}")
        continue
    frames.append(clean_noaa_csv_verify(p))

ver_all = pd.concat(frames, ignore_index=True)
ver_city = (
    ver_all.groupby("observation_hour_local", dropna=True)
           .agg({
               "temp_c":"mean",
               "rh_percent":"mean",
               "wind_ms":"mean",
               "precip_mm":"sum",
               "visibility_km":"mean",
               "weather_code": safe_mode,
           })
           .reset_index()
           .sort_values("observation_hour_local")
           .reset_index(drop=True)
)

# Load saved parquet and align for comparison
local_pq = os.path.abspath(os.path.join("..","data","interim","noaa_hourly_citywide_2024.parquet"))
saved = pd.read_parquet(local_pq, engine="pyarrow").sort_values("observation_hour_local").reset_index(drop=True)

print("Shapes -> computed:", ver_city.shape, " saved:", saved.shape)

# Compare time labels
same_hours = ver_city["observation_hour_local"].equals(saved["observation_hour_local"])
print("Hour labels identical:", same_hours)

# Numeric diffs
numeric_cols=["temp_c","rh_percent","wind_ms","precip_mm","visibility_km"]
diffs={}
for c in numeric_cols:
    a=ver_city[c].to_numpy()
    b=saved[c].to_numpy()
    if len(a)==len(b):
        diffs[c] = float(np.nanmax(np.abs(a-b)))
    else:
        diffs[c] = np.nan
print("Max abs diff per column:", diffs)

# Weather code equality (string)
wc_equal = ver_city["weather_code"].fillna("").equals(saved["weather_code"].fillna(""))
print("Weather code identical:", wc_equal)

ok = same_hours and wc_equal and all((np.isnan(v) or v<1e-9) for v in diffs.values())
print("Verification PASSED:", ok)

Shapes -> computed: (8782, 7)  saved: (8782, 7)
Hour labels identical: True
Max abs diff per column: {'temp_c': 0.0, 'rh_percent': 0.0, 'wind_ms': 0.0, 'precip_mm': 0.0, 'visibility_km': 0.0}
Weather code identical: True
Verification PASSED: True

This step compares storage footprint of raw NOAA CSVs versus aggregated parquet.

In [19]:
# Storage size comparison (raw CSVs vs merged parquet)
import os
from pathlib import Path

raw_dir = Path(r"X:\\data\\raw\\noaa\\2024")
parquet_local = Path(os.path.abspath(os.path.join("..","data","interim","noaa_hourly_citywide_2024.parquet")))

raw_total = 0
for p in sorted(raw_dir.glob("station_*_2024.csv")):
    sz = p.stat().st_size
    raw_total += sz
    print(f"{p.name:32} {sz/1_000_000:8.2f} MB")

pq_size = parquet_local.stat().st_size
print("\nTotals:")
print(f"Raw CSV total:     {raw_total/1_000_000:.2f} MB")
print(f"Merged Parquet:    {pq_size/1_000_000:.2f} MB")
if raw_total>0:
    print(f"Compression ratio: {raw_total/pq_size:,.1f}x smaller")

print("\nWhy so small?")
print("- Aggregation: 43k+ station-hour rows → 8.8k city-hour rows")
print("- Fewer columns: we keep 6 numeric + 1 categorical")
print("- Parquet compression + encoding (dictionary/bit packing) is efficient for floats and sparse strings")

station_CentralPark_2024.csv         8.53 MB
station_JFK_2024.csv                 8.09 MB
station_LaGuardia_2024.csv           8.58 MB
station_Newark_2024.csv              9.47 MB
station_Teterboro_2024.csv           6.95 MB

Totals:
Raw CSV total:     41.62 MB
Merged Parquet:    0.16 MB
Compression ratio: 266.3x smaller

Why so small?
- Aggregation: 43k+ station-hour rows → 8.8k city-hour rows
- Fewer columns: we keep 6 numeric + 1 categorical
- Parquet compression + encoding (dictionary/bit packing) is efficient for floats and sparse strings

This step displays the first 50 rows from the saved NOAA aggregated parquet.

In [20]:
# Peek: first 50 rows from merged parquet
import os, pandas as pd
from IPython.display import display

local_pq = os.path.abspath(os.path.join("..", "data", "interim", "noaa_hourly_citywide_2024.parquet"))
print(f"Reading: {local_pq}")
df_peek = pd.read_parquet(local_pq, engine="pyarrow")
print(f"Rows: {len(df_peek):,} | Columns: {list(df_peek.columns)}")
display(df_peek.head(50))

Reading: c:\Users\juraj.madzunkov\Documents\C\DA\CA1\data\interim\noaa_hourly_citywide_2024.parquet
Rows: 8,782 | Columns: ['observation_hour_local', 'temp_c', 'rh_percent', 'wind_ms', 'precip_mm', 'visibility_km', 'weather_code']

,observation_hour_local,temp_c,rh_percent,wind_ms,precip_mm,visibility_km,weather_code
0,2023-12-31 19:00:00,40.400000,63.000000,5.40,0.00,10.000,-RA:02 |RA |RA
1,2023-12-31 20:00:00,40.000000,64.000000,5.20,0.00,9.988,None
2,2023-12-31 21:00:00,39.400000,67.000000,5.00,0.00,10.000,None
3,2023-12-31 22:00:00,39.000000,69.200000,3.20,0.00,10.000,None
4,2023-12-31 23:00:00,38.300000,71.900000,2.10,0.00,9.988,None
5,2024-01-01 00:00:00,38.400000,73.800000,4.40,0.00,10.000,-RA:02 |RA |RA
6,2024-01-01 01:00:00,38.000000,78.200000,3.80,0.01,9.600,-RA:02 |RA |RA
7,2024-01-01 02:00:00,37.500000,82.850000,3.35,0.02,9.788,||RA
8,2024-01-01 03:00:00,38.400000,81.800000,2.80,0.01,10.000,-RA:02 |RA |RA
9,2024-01-01 04:00:00,40.200000,76.100000,3.30,0.00,10.000,None
10,2024-01-01 05:00:00,41.900000,70.700000,3.50,0.00,9.988,None
11,2024-01-01 06:00:00,43.533333,65.733333,3.20,0.00,10.000,None
12,2024-01-01 07:00:00,44.800000,58.600000,2.40,0.00,10.000,None
13,2024-01-01 08:00:00,44.700000,57.000000,2.60,0.00,9.988,None
14,2024-01-01 09:00:00,45.000000,55.800000,4.40,0.00,10.000,None
15,2024-01-01 10:00:00,44.200000,57.800000,6.40,0.00,10.000,None
16,2024-01-01 11:00:00,42.500000,59.800000,7.30,0.00,9.988,None
17,2024-01-01 12:00:00,40.800000,61.400000,6.60,0.00,10.000,None
18,2024-01-01 13:00:00,39.400000,62.800000,6.60,0.00,10.000,None
19,2024-01-01 14:00:00,38.600000,64.100000,6.40,0.00,9.988,None
20,2024-01-01 15:00:00,37.000000,65.200000,7.20,0.00,10.000,None
21,2024-01-01 16:00:00,36.000000,63.600000,6.60,0.00,10.000,None
22,2024-01-01 17:00:00,35.000000,67.000000,7.40,0.00,9.988,None
23,2024-01-01 18:00:00,32.600000,70.600000,6.20,0.00,10.000,None
24,2024-01-01 19:00:00,31.600000,73.200000,6.20,0.00,10.000,None
25,2024-01-01 20:00:00,30.600000,71.600000,4.70,0.00,9.988,None
26,2024-01-01 21:00:00,29.600000,70.800000,5.20,0.00,10.000,None
27,2024-01-01 22:00:00,28.800000,70.600000,6.00,0.00,10.000,None
28,2024-01-01 23:00:00,28.200000,70.000000,5.70,0.00,9.988,None
29,2024-01-02 00:00:00,27.600000,70.400000,6.00,0.00,10.000,None
30,2024-01-02 01:00:00,27.000000,72.200000,6.20,0.00,10.000,None
31,2024-01-02 02:00:00,27.600000,70.500000,5.40,0.00,9.988,None
32,2024-01-02 03:00:00,29.800000,66.400000,4.80,0.00,10.000,None
33,2024-01-02 04:00:00,32.400000,62.000000,6.00,0.00,10.000,None
34,2024-01-02 05:00:00,34.700000,56.800000,7.50,0.00,9.988,None
35,2024-01-02 06:00:00,38.200000,49.600000,7.00,0.00,10.000,None
36,2024-01-02 07:00:00,39.800000,47.000000,8.20,0.00,10.000,None
37,2024-01-02 08:00:00,41.100000,46.000000,6.50,0.00,9.988,None
38,2024-01-02 09:00:00,42.200000,43.400000,7.40,0.00,10.000,None
39,2024-01-02 10:00:00,42.200000,43.200000,7.80,0.00,10.000,None
40,2024-01-02 11:00:00,40.500000,47.200000,6.10,0.00,9.988,None
41,2024-01-02 12:00:00,39.600000,49.600000,4.60,0.00,10.000,None
42,2024-01-02 13:00:00,38.600000,52.600000,4.60,0.00,10.000,None
43,2024-01-02 14:00:00,37.200000,56.200000,5.80,0.00,9.988,None
44,2024-01-02 15:00:00,36.400000,57.200000,6.40,0.00,10.000,None
45,2024-01-02 16:00:00,35.600000,59.600000,7.00,0.00,10.000,None
46,2024-01-02 17:00:00,34.400000,62.500000,5.00,0.00,9.988,None
47,2024-01-02 18:00:00,33.800000,64.400000,6.40,0.00,10.000,None
48,2024-01-02 19:00:00,33.400000,67.600000,7.60,0.00,10.000,None
49,2024-01-02 20:00:00,33.500000,68.200000,6.10,0.00,9.988,None

### Merge & Export NOAA + TLC datasets

This step reads monthly TLC parquet files, derives NYC local pickup hour, left-joins hourly NOAA weather, writes outputs locally, and then copies to X:.

In [4]:
import os
import pandas as pd
import numpy as np
from tqdm import tqdm

# === CONFIG ===
TLC_DIR = r"X:\data\raw\tlc\2024"
NOAA_PATH = r"X:\data\interim\noaa_hourly_citywide_2024.parquet"
# primary outputs on X: (copied after local write)
OUT_PARQUET = r"X:\data\processed\nyc_2024_trips_weather.parquet"
OUT_SAMPLE = r"X:\data\processed\nyc_2024_trips_weather_sample.csv"
# local canonical outputs in repo (write here first)
LOCAL_PARQUET = os.path.abspath(os.path.join("..","data","processed","nyc_2024_trips_weather.parquet"))
LOCAL_SAMPLE  = os.path.abspath(os.path.join("..","data","processed","nyc_2024_trips_weather_sample.csv"))

# Load NOAA hourly dataset
weather = pd.read_parquet(NOAA_PATH)
weather.rename(columns={"observation_hour_local": "pickup_hour_local"}, inplace=True)
print(f"Loaded weather rows: {len(weather):,}")

# Helper: robustly derive NYC local hour from a datetime-like series
def to_local_hour(series, tz="America/New_York"):
    s = pd.to_datetime(series, errors="coerce")
    # If tz-aware, convert to NY and drop tz; if tz-naive, assume local NY already
    if getattr(s.dt, "tz", None) is not None:
        s = s.dt.tz_convert(tz).dt.tz_localize(None)
    return s.dt.floor("h")

# Prepare list of monthly files
files = sorted([f for f in os.listdir(TLC_DIR) if f.endswith(".parquet")])

merged_parts = []
for file in tqdm(files, desc="Merging monthly TLC files"):
    path = os.path.join(TLC_DIR, file)
    print(f"Processing {file} ...")
    df = pd.read_parquet(
        path,
        columns=[
            "tpep_pickup_datetime",
            "PULocationID",
            "trip_distance",
            "fare_amount",
            "tip_amount",
            "total_amount",
            "payment_type",
        ],
    )
    # Convert pickup to NYC local hour (handles tz-aware/naive safely)
    df["pickup_hour_local"] = to_local_hour(df["tpep_pickup_datetime"])
    df.drop(columns=["tpep_pickup_datetime"], inplace=True)

    # Merge with weather (left join)
    merged = df.merge(weather, on="pickup_hour_local", how="left", indicator=True)
    merged["merge_status"] = np.where(merged["_merge"] == "both", "matched", "no_weather_for_hour")
    merged.drop(columns=["_merge"], inplace=True)

    merged_parts.append(merged)

# Concatenate all months (optional; can be huge)
df_final = pd.concat(merged_parts, ignore_index=True)
print(f"Final merged shape: {df_final.shape}")

# === Save outputs: local first, then copy to X: ===
# Ensure local directory exists
os.makedirs(os.path.dirname(LOCAL_PARQUET), exist_ok=True)
df_final.to_parquet(LOCAL_PARQUET, index=False)
print(f"✅ Saved local merged dataset → {LOCAL_PARQUET}")

# Save 50 k-row CSV sample locally
sample = df_final.sample(n=min(50_000, len(df_final)), random_state=42)
sample.to_csv(LOCAL_SAMPLE, index=False)
print(f"✅ Saved local sample CSV → {LOCAL_SAMPLE}")

# Copy to X: with small retry helper (self-contained)
import shutil, time
def copy_with_retries(src, dst, retries=5, delay=2.0):
    for i in range(1, retries+1):
        try:
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            # Remove existing to avoid read-only/lock rename issues
            if os.path.exists(dst):
                try:
                    os.remove(dst)
                except Exception:
                    pass
            shutil.copy2(src, dst)
            print(f"📤 Copied → {dst}")
            return True
        except PermissionError as e:
            print(f"Attempt {i}/{retries}: PermissionError copying to {dst}: {e}")
        except Exception as e:
            print(f"Attempt {i}/{retries}: Error copying to {dst}: {e}")
        time.sleep(delay)
    return False

ok_pq = copy_with_retries(LOCAL_PARQUET, OUT_PARQUET)
ok_csv = copy_with_retries(LOCAL_SAMPLE, OUT_SAMPLE)
print(f"Copy parquet ok: {ok_pq} | Copy sample ok: {ok_csv}")

Loaded weather rows: 8,782

Merging monthly TLC files:   0%|          | 0/12 [00:00<?, ?it/s]

Processing yellow_tripdata_2024-01.parquet ...

Merging monthly TLC files:   8%|▊         | 1/12 [00:01<00:13,  1.19s/it]

Processing yellow_tripdata_2024-02.parquet ...

Merging monthly TLC files:  17%|█▋        | 2/12 [00:02<00:11,  1.17s/it]

Processing yellow_tripdata_2024-03.parquet ...

Merging monthly TLC files:  25%|██▌       | 3/12 [00:03<00:11,  1.25s/it]

Processing yellow_tripdata_2024-04.parquet ...

Merging monthly TLC files:  33%|███▎      | 4/12 [00:05<00:10,  1.28s/it]

Processing yellow_tripdata_2024-05.parquet ...

Merging monthly TLC files:  42%|████▏     | 5/12 [00:06<00:09,  1.32s/it]

Processing yellow_tripdata_2024-06.parquet ...

Merging monthly TLC files:  50%|█████     | 6/12 [00:07<00:08,  1.34s/it]

Processing yellow_tripdata_2024-07.parquet ...

Merging monthly TLC files:  58%|█████▊    | 7/12 [00:08<00:06,  1.28s/it]

Processing yellow_tripdata_2024-08.parquet ...

Merging monthly TLC files:  67%|██████▋   | 8/12 [00:10<00:04,  1.24s/it]

Processing yellow_tripdata_2024-09.parquet ...

Merging monthly TLC files:  75%|███████▌  | 9/12 [00:11<00:04,  1.36s/it]

Processing yellow_tripdata_2024-10.parquet ...

Merging monthly TLC files:  83%|████████▎ | 10/12 [00:13<00:02,  1.47s/it]

Processing yellow_tripdata_2024-11.parquet ...

Merging monthly TLC files:  92%|█████████▏| 11/12 [00:15<00:01,  1.50s/it]

Processing yellow_tripdata_2024-12.parquet ...

Merging monthly TLC files: 100%|██████████| 12/12 [00:16<00:00,  1.38s/it]

Final merged shape: (41169720, 14)
✅ Saved local merged dataset → c:\Users\juraj.madzunkov\Documents\C\DA\CA1\data\processed\nyc_2024_trips_weather.parquet
✅ Saved local merged dataset → c:\Users\juraj.madzunkov\Documents\C\DA\CA1\data\processed\nyc_2024_trips_weather.parquet
✅ Saved local sample CSV → c:\Users\juraj.madzunkov\Documents\C\DA\CA1\data\processed\nyc_2024_trips_weather_sample.csv
✅ Saved local sample CSV → c:\Users\juraj.madzunkov\Documents\C\DA\CA1\data\processed\nyc_2024_trips_weather_sample.csv
📤 Copied → X:\data\processed\nyc_2024_trips_weather.parquet
📤 Copied → X:\data\processed\nyc_2024_trips_weather.parquet
📤 Copied → X:\data\processed\nyc_2024_trips_weather_sample.csv
Copy parquet ok: True | Copy sample ok: True
📤 Copied → X:\data\processed\nyc_2024_trips_weather_sample.csv
Copy parquet ok: True | Copy sample ok: True

#### Deeper merge validation
- Show that `pickup_hour_local` includes hours (format to YYYY-MM-DD HH:MM) and that preview only looked like a single day because many trips share the same hour.
- Compare a few sampled hours against the NOAA hourly parquet to verify weather columns align.
- Scan all row groups to validate: when `merge_status == 'no_weather_for_hour'` then all weather columns are null (should be ~100%).

This step reads Parquet metadata on X: and local, verifies required columns, spot-checks a row group, and confirms dtypes.

In [5]:
# Quick validity checks for merged dataset (schema + metadata + spot checks)
import os
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import pyarrow.dataset as ds
from IPython.display import display

X_PQ = r"X:\\data\\processed\\nyc_2024_trips_weather.parquet"
LOCAL_PQ = os.path.abspath(os.path.join("..","data","processed","nyc_2024_trips_weather.parquet"))

def parquet_meta(path):
    pf = pq.ParquetFile(path)
    names = pf.schema_arrow.names
    meta = {
        "path": path,
        "exists": os.path.exists(path),
        "num_rows": pf.metadata.num_rows,
        "num_row_groups": pf.metadata.num_row_groups,
        "num_columns": pf.metadata.num_columns,
        "columns": names,
        "created_by": pf.metadata.created_by,
    }
    return meta

def print_meta(label, meta):
    print(f"[{label}] -> {meta['path']}")
    print(f"  exists={meta['exists']} | rows={meta['num_rows']:,} | row_groups={meta['num_row_groups']} | columns={meta['num_columns']}")
    print(f"  first 10 cols: {meta['columns'][:10]}")
    if meta.get("created_by"):
        print(f"  created_by: {meta['created_by']}")
    print()

# 1) Parquet metadata check (no full data load)
meta_x = parquet_meta(X_PQ)
print_meta("X drive", meta_x)
if os.path.exists(LOCAL_PQ):
    meta_local = parquet_meta(LOCAL_PQ)
    print_meta("Local", meta_local)
    print("Row count equal (X vs Local):", meta_x["num_rows"] == meta_local["num_rows"])
    print("Column names equal (X vs Local):", set(meta_x["columns"]) == set(meta_local["columns"]))
else:
    print("Local parquet not found (skipping local comparison)")

# 2) Required columns presence
required_cols = {
    "pickup_hour_local","PULocationID","trip_distance","fare_amount","tip_amount","total_amount","payment_type",
    "temp_c","rh_percent","wind_ms","precip_mm","visibility_km","weather_code","merge_status",
}
missing = sorted(list(required_cols - set(meta_x["columns"])))
print("Missing required columns:", missing)

# 3) Spot-check first row group only (lightweight), consistency of merge_status vs weather nullness
pf = pq.ParquetFile(X_PQ)
cols_probe = [
    "pickup_hour_local","merge_status","temp_c","rh_percent","wind_ms","precip_mm","visibility_km","weather_code",
    "PULocationID","trip_distance","fare_amount","tip_amount","total_amount","payment_type",
 ]
rg0 = pf.read_row_group(0, columns=[c for c in cols_probe if c in meta_x["columns"]])
df_rg0 = rg0.to_pandas()
print(f"Row-group 0 sample -> rows={len(df_rg0):,}")
if "merge_status" in df_rg0.columns:
    vc = df_rg0["merge_status"].value_counts(dropna=False)
    print("merge_status (row-group 0):\n", vc)
    weather_cols = [c for c in ["temp_c","rh_percent","wind_ms","precip_mm","visibility_km","weather_code"] if c in df_rg0]
    if len(weather_cols):
        matched = df_rg0["merge_status"] == "matched"
        no_w = df_rg0["merge_status"] == "no_weather_for_hour"
        matched_all_nonnull = df_rg0.loc[matched, weather_cols].notna().all(axis=1).mean() if matched.any() else float("nan")
        now_all_null = df_rg0.loc[no_w, weather_cols].isna().all(axis=1).mean() if no_w.any() else float("nan")
        print(f"matched rows: {matched.sum():,} | share all weather non-null: {matched_all_nonnull:.3f}")
        print(f"no_weather_for_hour rows: {no_w.sum():,} | share all weather null: {now_all_null:.3f}")
else:
    print("merge_status column not found in row-group 0 sample")

# 4) Dtype sanity: pickup_hour_local should be datetime64[ns] in the sample
if "pickup_hour_local" in df_rg0.columns:
    print("pickup_hour_local dtype:", df_rg0["pickup_hour_local"].dtype)
    if str(df_rg0["pickup_hour_local"].dtype).startswith("datetime64"):
        print("✅ pickup_hour_local is datetime64[ns] (sample)")
    else:
        print("⚠ pickup_hour_local is not datetime64 (sample)")

[X drive] -> X:\\data\\processed\\nyc_2024_trips_weather.parquet
  exists=True | rows=41,169,720 | row_groups=40 | columns=14
  first 10 cols: ['PULocationID', 'trip_distance', 'fare_amount', 'tip_amount', 'total_amount', 'payment_type', 'pickup_hour_local', 'temp_c', 'rh_percent', 'wind_ms']
  created_by: parquet-cpp-arrow version 22.0.0

[Local] -> c:\Users\juraj.madzunkov\Documents\C\DA\CA1\data\processed\nyc_2024_trips_weather.parquet
  exists=True | rows=41,169,720 | row_groups=40 | columns=14
  first 10 cols: ['PULocationID', 'trip_distance', 'fare_amount', 'tip_amount', 'total_amount', 'payment_type', 'pickup_hour_local', 'temp_c', 'rh_percent', 'wind_ms']
  created_by: parquet-cpp-arrow version 22.0.0

Row count equal (X vs Local): True
Column names equal (X vs Local): True
Missing required columns: []
Row-group 0 sample -> rows=1,048,576
merge_status (row-group 0):
 merge_status
matched                1048573
no_weather_for_hour          3
Name: count, dtype: int64
matched rows: 1,048,573 | share all weather non-null: 0.294
no_weather_for_hour rows: 3 | share all weather null: 1.000
pickup_hour_local dtype: datetime64[us]
✅ pickup_hour_local is datetime64[ns] (sample)

This step previews the first 50 rows of the merged parquet directly from X: without loading the full file.

In [7]:
# Preview: first 50 rows from X: parquet without loading full dataset
import os, pyarrow.parquet as pq
from IPython.display import display
X_PQ = r"X:\\data\\processed\\nyc_2024_trips_weather.parquet"
print(f"Reading preview from: {X_PQ}")
pf = pq.ParquetFile(X_PQ)
tbl_rg0 = pf.read_row_group(0)  # read only first row group
n = min(50, tbl_rg0.num_rows)
tbl_head = tbl_rg0.slice(0, n)
df_head = tbl_head.to_pandas()
print(f"Preview rows: {len(df_head)} | Columns: {list(df_head.columns)}")
display(df_head)

Reading preview from: X:\\data\\processed\\nyc_2024_trips_weather.parquet
Preview rows: 50 | Columns: ['PULocationID', 'trip_distance', 'fare_amount', 'tip_amount', 'total_amount', 'payment_type', 'pickup_hour_local', 'temp_c', 'rh_percent', 'wind_ms', 'precip_mm', 'visibility_km', 'weather_code', 'merge_status']

,PULocationID,trip_distance,fare_amount,tip_amount,total_amount,payment_type,pickup_hour_local,temp_c,rh_percent,wind_ms,precip_mm,visibility_km,weather_code,merge_status
0,186,1.72,17.7,0.00,22.70,2,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
1,140,1.80,10.0,3.75,18.75,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
2,236,4.70,23.3,3.00,31.30,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
3,79,1.40,10.0,2.00,17.00,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
4,211,0.80,7.9,3.20,16.10,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
5,148,4.70,29.6,6.90,41.50,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
6,138,10.82,45.7,10.00,64.95,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
7,246,3.00,25.4,0.00,30.40,2,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
8,161,5.44,31.0,0.00,36.00,2,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
9,113,0.04,3.0,0.00,8.00,2,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
10,107,0.75,7.9,0.00,12.90,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
11,158,1.20,14.9,3.95,23.85,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
12,246,8.20,59.0,14.15,85.09,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
13,68,0.40,5.8,1.25,12.05,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
14,90,0.80,6.5,0.00,11.50,2,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
15,132,5.00,21.2,0.00,25.45,2,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
16,164,1.50,12.8,4.45,22.25,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
17,237,0.00,3.0,0.00,8.00,2,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
18,141,1.50,9.3,3.00,17.30,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
19,161,2.57,17.7,10.00,32.70,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
20,263,0.66,6.5,2.88,14.38,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
21,246,1.70,29.6,6.90,41.50,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
22,158,0.94,8.6,2.72,16.32,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
23,236,0.00,3.0,0.00,8.00,2,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
24,263,23.90,120.0,0.00,127.94,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
25,148,1.08,8.6,2.72,16.32,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
26,4,5.88,28.9,2.50,36.40,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
27,238,2.22,13.5,0.00,18.50,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
28,239,5.10,28.9,0.00,33.90,2,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
29,233,2.09,12.8,3.56,21.36,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
30,79,8.89,47.8,7.92,60.72,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
31,162,2.10,14.2,3.80,23.00,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
32,262,11.51,44.3,11.25,67.49,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
33,239,1.79,19.8,0.00,24.80,2,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
34,137,2.50,12.1,0.00,17.10,2,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
35,140,1.60,9.3,3.55,17.85,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
36,236,1.10,7.9,0.00,12.90,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
37,238,0.70,6.5,2.30,13.80,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
38,142,1.10,8.6,0.00,13.60,4,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
39,229,2.96,14.9,3.98,23.88,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
40,186,1.20,16.3,4.26,25.56,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
41,68,2.42,23.3,0.00,28.30,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
42,113,5.28,31.0,7.20,43.20,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
43,238,1.47,10.0,2.00,17.00,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
44,239,2.41,14.2,3.84,23.04,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
45,142,1.04,7.9,0.00,12.90,2,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
46,163,2.41,17.7,4.54,27.24,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
47,246,1.06,11.4,0.00,16.40,2,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
48,234,0.83,8.6,3.40,17.00,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
49,114,1.94,14.9,3.98,23.88,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched

This step lists unique-hour counts and top hours for the first and last row groups to demonstrate hour-level labels.

In [8]:
# Show hour resolution explicitly for first/last row groups
import pyarrow.parquet as pq
from datetime import datetime
X_PQ = r"X:\\data\\processed\\nyc_2024_trips_weather.parquet"
pf = pq.ParquetFile(X_PQ)
n_rg = pf.metadata.num_row_groups
def hours_from_rg(idx, take=10000):
    tbl = pf.read_row_group(idx, columns=["pickup_hour_local"])
    dfh = tbl.to_pandas()
    # format to show hour explicitly
    s = pd.to_datetime(dfh["pickup_hour_local"]).dt.strftime("%Y-%m-%d %H:%M")
    vc = s.value_counts()
    return vc.head(10), s.nunique()
vc0, u0 = hours_from_rg(0)
vcl, ul = hours_from_rg(n_rg-1)
print(f"Row group count: {n_rg}")
print("First RG -> unique hours:", u0)
print(vc0)
print("\nLast RG  -> unique hours:", ul)
print(vcl)

Row group count: 40
First RG -> unique hours: 296
pickup_hour_local
2024-01-04 18:00    8529
2024-01-04 17:00    8154
2024-01-11 18:00    7587
2024-01-05 17:00    7391
2024-01-04 16:00    7359
2024-01-11 17:00    7356
2024-01-05 18:00    7277
2024-01-11 19:00    7064
2024-01-10 18:00    7056
2024-01-09 17:00    7049
Name: count, dtype: int64

Last RG  -> unique hours: 604
pickup_hour_local
2024-12-31 22:00    2277
2024-12-31 21:00    2131
2024-12-14 18:00    1499
2024-12-21 18:00    1493
2024-12-14 19:00    1485
2024-12-13 20:00    1450
2024-12-20 18:00    1440
2024-12-14 20:00    1439
2024-12-18 19:00    1435
2024-12-07 23:00    1424
Name: count, dtype: int64

This step samples several hours across the year and verifies numeric weather equality (processed vs NOAA).

In [9]:
# Verify weather alignment for a few sampled hours (early/mid/late)
import numpy as np, pandas as pd, pyarrow.parquet as pq
from datetime import timedelta
PROC_PQ = r"X:\\data\\processed\\nyc_2024_trips_weather.parquet"
NOAA_PQ = r"X:\\data\\interim\\noaa_hourly_citywide_2024.parquet"
pf = pq.ParquetFile(PROC_PQ)
# sample: pick one hour from RG0 and one from the last RG; also try mid RG if available
samples = []
def pick_one_hour_from_rg(pf, rg_index):
    tbl = pf.read_row_group(rg_index, columns=["pickup_hour_local"])
    s = pd.to_datetime(tbl.to_pandas()["pickup_hour_local"])
    if len(s)==0:
        return None
    # choose median row to avoid extreme skew
    return s.iloc[len(s)//2]
first_hour = pick_one_hour_from_rg(pf, 0)
last_hour = pick_one_hour_from_rg(pf, max(0, pf.metadata.num_row_groups-1))
mid_rg = pf.metadata.num_row_groups//2
mid_hour = pick_one_hour_from_rg(pf, mid_rg) if pf.metadata.num_row_groups>2 else None
for h in [first_hour, mid_hour, last_hour]:
    if h is not None:
        samples.append(h)
print("Sampled hours:", [str(h) for h in samples])
# build small frames around these hours from processed file
def load_processed_for_hours(hours):
    out=[]
    for h in hours:
        # read row groups and filter in pandas (small number of hours; quick)
        for i in range(pf.metadata.num_row_groups):
            tbl = pf.read_row_group(i, columns=["pickup_hour_local","temp_c","rh_percent","wind_ms","precip_mm","visibility_km","weather_code","merge_status"])
            df = tbl.to_pandas()
            mask = pd.to_datetime(df["pickup_hour_local"]).isin([h])
            if mask.any():
                out.append(df.loc[mask])
    return pd.concat(out, ignore_index=True) if out else pd.DataFrame()
proc_sample = load_processed_for_hours(samples)
print(f"Processed rows for sampled hours: {len(proc_sample):,}")
# load NOAA hourly and compare values for those hours
noaa = pd.read_parquet(NOAA_PQ)
noaa.rename(columns={"observation_hour_local":"pickup_hour_local"}, inplace=True)
noaa_sub = noaa[noaa["pickup_hour_local"].isin(samples)].copy()
# aggregate processed by hour (weather columns should be constant per hour)
weather_cols=["temp_c","rh_percent","wind_ms","precip_mm","visibility_km","weather_code"]
agg_proc = (proc_sample.groupby("pickup_hour_local")[weather_cols].agg({c:"nunique" for c in weather_cols}).rename(columns=lambda c:f"{c}_nuniq").reset_index())
print("Distinct weather values per hour in processed sample:\n", agg_proc)
# join and check equality
merged_chk = proc_sample.merge(noaa_sub, on="pickup_hour_local", suffixes=("_proc","_noaa"), how="left")
eq = {}
for c in weather_cols:
    a = merged_chk[f"{c}_proc"]
    b = merged_chk[f"{c}_noaa"]
    eq[c] = float((a.fillna(np.nan)==b.fillna(np.nan)).mean())
print("Share of rows equal for each weather column (proc vs NOAA):", eq)

Sampled hours: ['2024-01-07 02:00:00', '2024-07-14 21:00:00', '2024-12-17 07:00:00']
Processed rows for sampled hours: 10,779
Distinct weather values per hour in processed sample:
     pickup_hour_local  temp_c_nuniq  rh_percent_nuniq  wind_ms_nuniq  \
0 2024-01-07 02:00:00             1                 1              1
1 2024-07-14 21:00:00             1                 1              1
2 2024-12-17 07:00:00             1                 1              1

   precip_mm_nuniq  visibility_km_nuniq  weather_code_nuniq
0                1                    1                   1
1                1                    1                   0
2                1                    1                   0
Share of rows equal for each weather column (proc vs NOAA): {'temp_c': 1.0, 'rh_percent': 1.0, 'wind_ms': 1.0, 'precip_mm': 1.0, 'visibility_km': 1.0, 'weather_code': 0.17895908711383246}

This step scans all row groups to confirm that rows labeled 'no_weather_for_hour' have weather columns null, and 'matched' rows have weather populated where available.

In [10]:
# Global consistency: scan row groups for weather-null logic by merge_status
import numpy as np, pyarrow.parquet as pq
PROC_PQ = r"X:\\data\\processed\\nyc_2024_trips_weather.parquet"
pf = pq.ParquetFile(PROC_PQ)
weather_cols=["temp_c","rh_percent","wind_ms","precip_mm","visibility_km","weather_code"]
tot=0; no_w_tot=0; no_w_allnull=0; matched_tot=0; matched_allnonnull=0
for i in range(pf.metadata.num_row_groups):
    tbl = pf.read_row_group(i, columns=["merge_status"]+weather_cols)
    df = tbl.to_pandas()
    tot += len(df)
    m_no = df["merge_status"]=="no_weather_for_hour"
    m_ok = df["merge_status"]=="matched"
    no_w_tot += m_no.sum()
    matched_tot += m_ok.sum()
    no_w_allnull += df.loc[m_no, weather_cols].isna().all(axis=1).sum()
    matched_allnonnull += df.loc[m_ok, weather_cols].notna().all(axis=1).sum()
print(f"Rows total: {tot:,}")
print(f"no_weather_for_hour rows: {no_w_tot:,} | share all weather null: {no_w_allnull/max(1,no_w_tot):.3f}")
print(f"matched rows: {matched_tot:,} | share all weather non-null: {matched_allnonnull/max(1,matched_tot):.3f}")

Rows total: 41,169,720
no_weather_for_hour rows: 41,211 | share all weather null: 1.000
matched rows: 41,128,509 | share all weather non-null: 0.268

#### Processed vs NOAA by hour — compact report
This step aggregates processed trips per hour and compares numeric weather columns to NOAA across 2024.

In [11]:
# Build hour-level report: processed (X: processed parquet) vs NOAA (X: interim parquet)
import os, numpy as np, pandas as pd, pyarrow.parquet as pq
from math import isfinite
PROC_PQ = r"X:\\data\\processed\\nyc_2024_trips_weather.parquet"
NOAA_PQ = r"X:\\data\\interim\\noaa_hourly_citywide_2024.parquet"
numeric_cols = ["temp_c","rh_percent","wind_ms","precip_mm","visibility_km"]
# --- Load NOAA (small) ---
noaa = pd.read_parquet(NOAA_PQ)
noaa = noaa.rename(columns={"observation_hour_local":"hour"})[["hour"]+numeric_cols].copy()
noaa_hours = set(noaa["hour"].astype("datetime64[ns]").tolist())
# --- Scan processed parquet by row group; aggregate per hour ---
pf = pq.ParquetFile(PROC_PQ)
parts = []
for i in range(pf.metadata.num_row_groups):
    tbl = pf.read_row_group(i, columns=["pickup_hour_local"]+numeric_cols)
    df = tbl.to_pandas()
    df = df.rename(columns={"pickup_hour_local":"hour"})
    # Mean is safe because hour-level weather is constant for a given hour; NaNs are ignored
    part = df.groupby("hour", as_index=False)[numeric_cols].mean()
    parts.append(part)
proc = pd.concat(parts, ignore_index=True)
proc = proc.groupby("hour", as_index=False)[numeric_cols].mean()  # reconcile across row groups
proc_hours = set(proc["hour"].astype("datetime64[ns]").tolist())
# --- Coverage ---
missing_in_proc = sorted(list(noaa_hours - proc_hours))
missing_in_noaa = sorted(list(proc_hours - noaa_hours))
print("Coverage:")
print(f"  NOAA hours:       {len(noaa_hours):,}")
print(f"  Processed hours:  {len(proc_hours):,}")
print(f"  Intersection:     {len(noaa_hours & proc_hours):,}")
print(f"  Missing in proc:  {len(missing_in_proc)}", ("→ e.g.," , missing_in_proc[:3]) if missing_in_proc[:3] else "")
print(f"  Missing in NOAA:  {len(missing_in_noaa)}", ("→ e.g.," , missing_in_noaa[:3]) if missing_in_noaa[:3] else "")
# --- Join and compute equality metrics ---
merged = noaa.merge(proc, on="hour", how="inner", suffixes=("_noaa","_proc"))
report = {}
for c in numeric_cols:
    a = merged[f"{c}_noaa"].to_numpy()
    b = merged[f"{c}_proc"].to_numpy()
    eq = np.isclose(a, b, equal_nan=True, atol=1e-9)
    share = float(np.mean(eq)) if len(eq) else float("nan")
    # max absolute diff over valid comparisons
    diffs = np.abs(a - b)
    diffs = diffs[np.isfinite(diffs)] if len(diffs) else diffs
    maxdiff = float(diffs.max()) if len(diffs) else float("nan")
    report[c] = {"share_equal": share, "max_abs_diff": maxdiff}
print("\nEquality by numeric column (processed vs NOAA over intersection):")
for c, stats in report.items():
    print(f"  {c:14} share_equal={stats['share_equal']:.6f}  max_abs_diff={stats['max_abs_diff']:.3g}")
# --- Verdict ---
all_equal = all((np.isnan(v["share_equal"]) or v["share_equal"]==1.0) for v in report.values())
print("\nVerdict:")
print("  Numeric weather columns match NOAA per hour:" , all_equal)
if not all_equal:
    print("  Note: small float differences or NaNs in NOAA can reduce equality; see max_abs_diff above.")

Coverage:
  NOAA hours:       8,782
  Processed hours:  8,802
  Intersection:     8,778
  Missing in proc:  4 ('→ e.g.,', [Timestamp('2023-12-31 19:00:00'), Timestamp('2023-12-31 20:00:00'), Timestamp('2023-12-31 21:00:00')])
  Missing in NOAA:  24 ('→ e.g.,', [Timestamp('2002-12-31 16:00:00'), Timestamp('2002-12-31 22:00:00'), Timestamp('2002-12-31 23:00:00')])

Equality by numeric column (processed vs NOAA over intersection):
  temp_c         share_equal=1.000000  max_abs_diff=1.42e-14
  rh_percent     share_equal=1.000000  max_abs_diff=1.42e-14
  wind_ms        share_equal=1.000000  max_abs_diff=3.55e-15
  precip_mm      share_equal=1.000000  max_abs_diff=4.44e-16
  visibility_km  share_equal=1.000000  max_abs_diff=1.78e-15

Verdict:
  Numeric weather columns match NOAA per hour: True

### Final Dataset Stats & Integrity

In [12]:
import pandas as pd

FILE = r"X:\data\processed\nyc_2024_trips_weather.parquet"
df = pd.read_parquet(FILE)

print(df.dtypes)
print(df.shape)
df.head(3)

PULocationID                  int32
trip_distance               float64
fare_amount                 float64
tip_amount                  float64
total_amount                float64
payment_type                  int64
pickup_hour_local    datetime64[us]
temp_c                      float64
rh_percent                  float64
wind_ms                     float64
precip_mm                   float64
visibility_km               float64
weather_code                 object
merge_status                 object
dtype: object
(41169720, 14)

,PULocationID,trip_distance,fare_amount,tip_amount,total_amount,payment_type,pickup_hour_local,temp_c,rh_percent,wind_ms,precip_mm,visibility_km,weather_code,merge_status
0,186,1.72,17.7,0.00,22.70,2,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
1,140,1.80,10.0,3.75,18.75,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched
2,236,4.70,23.3,3.00,31.30,1,2024-01-01,38.4,73.8,4.4,0.0,10.0,-RA:02 |RA |RA,matched

In [13]:
# Row and column counts
print("Shape:", df.shape)

# Null percentages
nulls = df.isna().mean().mul(100).round(2)
print("\nMissing values (%)\n", nulls)

# merge_status summary
print("\nMerge status counts:")
print(df["merge_status"].value_counts(normalize=True).mul(100).round(2))

Shape: (41169720, 14)

Missing values (%)
 PULocationID          0.00
trip_distance         0.00
fare_amount           0.00
tip_amount            0.00
total_amount          0.00
payment_type          0.00
pickup_hour_local     0.00
temp_c                0.10
rh_percent            0.10
wind_ms               0.10
precip_mm             0.10
visibility_km         0.10
weather_code         73.22
merge_status          0.00
dtype: float64

Merge status counts:
merge_status
matched                99.9
no_weather_for_hour     0.1
Name: proportion, dtype: float64

Missing values (%)
 PULocationID          0.00
trip_distance         0.00
fare_amount           0.00
tip_amount            0.00
total_amount          0.00
payment_type          0.00
pickup_hour_local     0.00
temp_c                0.10
rh_percent            0.10
wind_ms               0.10
precip_mm             0.10
visibility_km         0.10
weather_code         73.22
merge_status          0.00
dtype: float64

Merge status counts:
merge_status
matched                99.9
no_weather_for_hour     0.1
Name: proportion, dtype: float64

In [14]:
print(df[["temp_c","rh_percent","wind_ms","precip_mm","visibility_km"]].describe())

             temp_c    rh_percent       wind_ms     precip_mm  visibility_km
count  4.112851e+07  4.112851e+07  4.112851e+07  4.112851e+07   4.112851e+07
mean   5.617770e+01  6.299855e+01  7.346373e+00  5.088441e-02   9.315365e+00
std    1.662680e+01  1.776533e+01  4.020007e+00  3.129308e-01   1.674712e+00
min    8.600000e+00  1.960000e+01  0.000000e+00  0.000000e+00   4.375000e-01
25%    4.316667e+01  4.920000e+01  4.400000e+00  0.000000e+00   9.800000e+00
50%    5.640000e+01  6.260000e+01  6.800000e+00  0.000000e+00   1.000000e+01
75%    6.990000e+01  7.760000e+01  9.600000e+00  0.000000e+00   1.000000e+01
max    9.460000e+01  9.640000e+01  2.720000e+01  1.022000e+01   1.000000e+01

## Notebook summary and outputs
This notebook performs:
- Download TLC 2024 monthly trip parquet files to X: and validate presence.
- Download NOAA 2024 station CSVs, clean to NYC local time, aggregate to citywide hourly metrics, and save parquet (local → copy to X:).
- Validate NOAA parquet (parity, structure, coverage, recomputation, and size).
- Merge TLC trips with hourly NOAA weather (NYC local hour join) and save merged outputs (local → copy to X:).
- Validate merged dataset (metadata checks, hour-level sampling, global invariants, and full-hour report vs NOAA).

Resulting artifacts:
- NOAA aggregated parquet (local): ../data/interim/noaa_hourly_citywide_2024.parquet
- NOAA aggregated parquet (X:): X:\\data\\interim\\noaa_hourly_citywide_2024.parquet
- Merged trips+weather parquet (local): ../data/processed/nyc_2024_trips_weather.parquet
- Merged trips+weather parquet (X:): X:\\data\\processed\\nyc_2024_trips_weather.parquet
- Sample of merged (local): ../data/processed/nyc_2024_trips_weather_sample.csv
- Sample of merged (X:): X:\\data\\processed\\nyc_2024_trips_weather_sample.csv